// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_S006SRVIMUREPLAYMSG_H_
#define FLATBUFFERS_GENERATED_S006SRVIMUREPLAYMSG_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

struct Vec3Msg;
struct Vec3MsgBuilder;
struct Vec3MsgT;

struct Vec4Msg;
struct Vec4MsgBuilder;
struct Vec4MsgT;

struct SrvIMUReplayMsg;
struct SrvIMUReplayMsgBuilder;
struct SrvIMUReplayMsgT;

struct Vec3MsgT : public ::flatbuffers::NativeTable {
  typedef Vec3Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
};

struct Vec3Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec3MsgT NativeTableType;
  typedef Vec3MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
  Vec3MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec3Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec3MsgBuilder {
  typedef Vec3Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec3Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec3Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec3Msg::VT_Z, z, 0.0f);
  }
  explicit Vec3MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec3Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec3Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f) {
  Vec3MsgBuilder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct Vec4MsgT : public ::flatbuffers::NativeTable {
  typedef Vec4Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
  float w = 0.0f;
};

struct Vec4Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec4MsgT NativeTableType;
  typedef Vec4MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8,
    VT_W = 10
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  float w() const {
    return GetField<float>(VT_W, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           VerifyField<float>(verifier, VT_W, 4) &&
           verifier.EndTable();
  }
  Vec4MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec4Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec4MsgBuilder {
  typedef Vec4Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec4Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec4Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec4Msg::VT_Z, z, 0.0f);
  }
  void add_w(float w) {
    fbb_.AddElement<float>(Vec4Msg::VT_W, w, 0.0f);
  }
  explicit Vec4MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec4Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec4Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f,
    float w = 0.0f) {
  Vec4MsgBuilder builder_(_fbb);
  builder_.add_w(w);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SrvIMUReplayMsgT : public ::flatbuffers::NativeTable {
  typedef SrvIMUReplayMsg TableType;
  double timestamp = 0.0;
  std::string name{};
  uint32_t sys_id = 0;
  uint32_t req_src_id = 0;
  bool set_replay = false;
  std::vector<float> timestamp_gt{};
  std::vector<std::unique_ptr<Vec3MsgT>> euler_est{};
  std::vector<std::unique_ptr<Vec3MsgT>> euler_gt{};
  SrvIMUReplayMsgT() = default;
  SrvIMUReplayMsgT(const SrvIMUReplayMsgT &o);
  SrvIMUReplayMsgT(SrvIMUReplayMsgT&&) FLATBUFFERS_NOEXCEPT = default;
  SrvIMUReplayMsgT &operator=(SrvIMUReplayMsgT o) FLATBUFFERS_NOEXCEPT;
};

struct SrvIMUReplayMsg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SrvIMUReplayMsgT NativeTableType;
  typedef SrvIMUReplayMsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_NAME = 6,
    VT_SYS_ID = 8,
    VT_REQ_SRC_ID = 10,
    VT_SET_REPLAY = 12,
    VT_TIMESTAMP_GT = 14,
    VT_EULER_EST = 16,
    VT_EULER_GT = 18
  };
  double timestamp() const {
    return GetField<double>(VT_TIMESTAMP, 0.0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint32_t sys_id() const {
    return GetField<uint32_t>(VT_SYS_ID, 0);
  }
  uint32_t req_src_id() const {
    return GetField<uint32_t>(VT_REQ_SRC_ID, 0);
  }
  bool set_replay() const {
    return GetField<uint8_t>(VT_SET_REPLAY, 0) != 0;
  }
  const ::flatbuffers::Vector<float> *timestamp_gt() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_TIMESTAMP_GT);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Vec3Msg>> *euler_est() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Vec3Msg>> *>(VT_EULER_EST);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Vec3Msg>> *euler_gt() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Vec3Msg>> *>(VT_EULER_GT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_TIMESTAMP, 8) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint32_t>(verifier, VT_SYS_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_REQ_SRC_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_SET_REPLAY, 1) &&
           VerifyOffset(verifier, VT_TIMESTAMP_GT) &&
           verifier.VerifyVector(timestamp_gt()) &&
           VerifyOffset(verifier, VT_EULER_EST) &&
           verifier.VerifyVector(euler_est()) &&
           verifier.VerifyVectorOfTables(euler_est()) &&
           VerifyOffset(verifier, VT_EULER_GT) &&
           verifier.VerifyVector(euler_gt()) &&
           verifier.VerifyVectorOfTables(euler_gt()) &&
           verifier.EndTable();
  }
  SrvIMUReplayMsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SrvIMUReplayMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SrvIMUReplayMsg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SrvIMUReplayMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SrvIMUReplayMsgBuilder {
  typedef SrvIMUReplayMsg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(double timestamp) {
    fbb_.AddElement<double>(SrvIMUReplayMsg::VT_TIMESTAMP, timestamp, 0.0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(SrvIMUReplayMsg::VT_NAME, name);
  }
  void add_sys_id(uint32_t sys_id) {
    fbb_.AddElement<uint32_t>(SrvIMUReplayMsg::VT_SYS_ID, sys_id, 0);
  }
  void add_req_src_id(uint32_t req_src_id) {
    fbb_.AddElement<uint32_t>(SrvIMUReplayMsg::VT_REQ_SRC_ID, req_src_id, 0);
  }
  void add_set_replay(bool set_replay) {
    fbb_.AddElement<uint8_t>(SrvIMUReplayMsg::VT_SET_REPLAY, static_cast<uint8_t>(set_replay), 0);
  }
  void add_timestamp_gt(::flatbuffers::Offset<::flatbuffers::Vector<float>> timestamp_gt) {
    fbb_.AddOffset(SrvIMUReplayMsg::VT_TIMESTAMP_GT, timestamp_gt);
  }
  void add_euler_est(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Vec3Msg>>> euler_est) {
    fbb_.AddOffset(SrvIMUReplayMsg::VT_EULER_EST, euler_est);
  }
  void add_euler_gt(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Vec3Msg>>> euler_gt) {
    fbb_.AddOffset(SrvIMUReplayMsg::VT_EULER_GT, euler_gt);
  }
  explicit SrvIMUReplayMsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SrvIMUReplayMsg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SrvIMUReplayMsg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SrvIMUReplayMsg> CreateSrvIMUReplayMsg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double timestamp = 0.0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint32_t sys_id = 0,
    uint32_t req_src_id = 0,
    bool set_replay = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> timestamp_gt = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Vec3Msg>>> euler_est = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Vec3Msg>>> euler_gt = 0) {
  SrvIMUReplayMsgBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_euler_gt(euler_gt);
  builder_.add_euler_est(euler_est);
  builder_.add_timestamp_gt(timestamp_gt);
  builder_.add_req_src_id(req_src_id);
  builder_.add_sys_id(sys_id);
  builder_.add_name(name);
  builder_.add_set_replay(set_replay);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SrvIMUReplayMsg> CreateSrvIMUReplayMsgDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double timestamp = 0.0,
    const char *name = nullptr,
    uint32_t sys_id = 0,
    uint32_t req_src_id = 0,
    bool set_replay = false,
    const std::vector<float> *timestamp_gt = nullptr,
    const std::vector<::flatbuffers::Offset<Vec3Msg>> *euler_est = nullptr,
    const std::vector<::flatbuffers::Offset<Vec3Msg>> *euler_gt = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto timestamp_gt__ = timestamp_gt ? _fbb.CreateVector<float>(*timestamp_gt) : 0;
  auto euler_est__ = euler_est ? _fbb.CreateVector<::flatbuffers::Offset<Vec3Msg>>(*euler_est) : 0;
  auto euler_gt__ = euler_gt ? _fbb.CreateVector<::flatbuffers::Offset<Vec3Msg>>(*euler_gt) : 0;
  return CreateSrvIMUReplayMsg(
      _fbb,
      timestamp,
      name__,
      sys_id,
      req_src_id,
      set_replay,
      timestamp_gt__,
      euler_est__,
      euler_gt__);
}

::flatbuffers::Offset<SrvIMUReplayMsg> CreateSrvIMUReplayMsg(::flatbuffers::FlatBufferBuilder &_fbb, const SrvIMUReplayMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline Vec3MsgT *Vec3Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec3MsgT>(new Vec3MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec3Msg::UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
}

inline ::flatbuffers::Offset<Vec3Msg> Vec3Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec3Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec3MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  return CreateVec3Msg(
      _fbb,
      _x,
      _y,
      _z);
}

inline Vec4MsgT *Vec4Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec4MsgT>(new Vec4MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec4Msg::UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
  { auto _e = w(); _o->w = _e; }
}

inline ::flatbuffers::Offset<Vec4Msg> Vec4Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec4Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec4MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  auto _w = _o->w;
  return CreateVec4Msg(
      _fbb,
      _x,
      _y,
      _z,
      _w);
}

inline SrvIMUReplayMsgT::SrvIMUReplayMsgT(const SrvIMUReplayMsgT &o)
      : timestamp(o.timestamp),
        name(o.name),
        sys_id(o.sys_id),
        req_src_id(o.req_src_id),
        set_replay(o.set_replay),
        timestamp_gt(o.timestamp_gt) {
  euler_est.reserve(o.euler_est.size());
  for (const auto &euler_est_ : o.euler_est) { euler_est.emplace_back((euler_est_) ? new Vec3MsgT(*euler_est_) : nullptr); }
  euler_gt.reserve(o.euler_gt.size());
  for (const auto &euler_gt_ : o.euler_gt) { euler_gt.emplace_back((euler_gt_) ? new Vec3MsgT(*euler_gt_) : nullptr); }
}

inline SrvIMUReplayMsgT &SrvIMUReplayMsgT::operator=(SrvIMUReplayMsgT o) FLATBUFFERS_NOEXCEPT {
  std::swap(timestamp, o.timestamp);
  std::swap(name, o.name);
  std::swap(sys_id, o.sys_id);
  std::swap(req_src_id, o.req_src_id);
  std::swap(set_replay, o.set_replay);
  std::swap(timestamp_gt, o.timestamp_gt);
  std::swap(euler_est, o.euler_est);
  std::swap(euler_gt, o.euler_gt);
  return *this;
}

inline SrvIMUReplayMsgT *SrvIMUReplayMsg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SrvIMUReplayMsgT>(new SrvIMUReplayMsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SrvIMUReplayMsg::UnPackTo(SrvIMUReplayMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = timestamp(); _o->timestamp = _e; }
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = sys_id(); _o->sys_id = _e; }
  { auto _e = req_src_id(); _o->req_src_id = _e; }
  { auto _e = set_replay(); _o->set_replay = _e; }
  { auto _e = timestamp_gt(); if (_e) { _o->timestamp_gt.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->timestamp_gt[_i] = _e->Get(_i); } } else { _o->timestamp_gt.resize(0); } }
  { auto _e = euler_est(); if (_e) { _o->euler_est.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->euler_est[_i]) { _e->Get(_i)->UnPackTo(_o->euler_est[_i].get(), _resolver); } else { _o->euler_est[_i] = std::unique_ptr<Vec3MsgT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->euler_est.resize(0); } }
  { auto _e = euler_gt(); if (_e) { _o->euler_gt.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->euler_gt[_i]) { _e->Get(_i)->UnPackTo(_o->euler_gt[_i].get(), _resolver); } else { _o->euler_gt[_i] = std::unique_ptr<Vec3MsgT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->euler_gt.resize(0); } }
}

inline ::flatbuffers::Offset<SrvIMUReplayMsg> SrvIMUReplayMsg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SrvIMUReplayMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSrvIMUReplayMsg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SrvIMUReplayMsg> CreateSrvIMUReplayMsg(::flatbuffers::FlatBufferBuilder &_fbb, const SrvIMUReplayMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SrvIMUReplayMsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _timestamp = _o->timestamp;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _sys_id = _o->sys_id;
  auto _req_src_id = _o->req_src_id;
  auto _set_replay = _o->set_replay;
  auto _timestamp_gt = _o->timestamp_gt.size() ? _fbb.CreateVector(_o->timestamp_gt) : 0;
  auto _euler_est = _o->euler_est.size() ? _fbb.CreateVector<::flatbuffers::Offset<Vec3Msg>> (_o->euler_est.size(), [](size_t i, _VectorArgs *__va) { return CreateVec3Msg(*__va->__fbb, __va->__o->euler_est[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _euler_gt = _o->euler_gt.size() ? _fbb.CreateVector<::flatbuffers::Offset<Vec3Msg>> (_o->euler_gt.size(), [](size_t i, _VectorArgs *__va) { return CreateVec3Msg(*__va->__fbb, __va->__o->euler_gt[i].get(), __va->__rehasher); }, &_va ) : 0;
  return CreateSrvIMUReplayMsg(
      _fbb,
      _timestamp,
      _name,
      _sys_id,
      _req_src_id,
      _set_replay,
      _timestamp_gt,
      _euler_est,
      _euler_gt);
}

inline const SrvIMUReplayMsg *GetSrvIMUReplayMsg(const void *buf) {
  return ::flatbuffers::GetRoot<SrvIMUReplayMsg>(buf);
}

inline const SrvIMUReplayMsg *GetSizePrefixedSrvIMUReplayMsg(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SrvIMUReplayMsg>(buf);
}

inline const char *SrvIMUReplayMsgIdentifier() {
  return "S006";
}

inline bool SrvIMUReplayMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SrvIMUReplayMsgIdentifier());
}

inline bool SizePrefixedSrvIMUReplayMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SrvIMUReplayMsgIdentifier(), true);
}

inline bool VerifySrvIMUReplayMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SrvIMUReplayMsg>(SrvIMUReplayMsgIdentifier());
}

inline bool VerifySizePrefixedSrvIMUReplayMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SrvIMUReplayMsg>(SrvIMUReplayMsgIdentifier());
}

inline void FinishSrvIMUReplayMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SrvIMUReplayMsg> root) {
  fbb.Finish(root, SrvIMUReplayMsgIdentifier());
}

inline void FinishSizePrefixedSrvIMUReplayMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SrvIMUReplayMsg> root) {
  fbb.FinishSizePrefixed(root, SrvIMUReplayMsgIdentifier());
}

inline std::unique_ptr<SrvIMUReplayMsgT> UnPackSrvIMUReplayMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SrvIMUReplayMsgT>(GetSrvIMUReplayMsg(buf)->UnPack(res));
}

inline std::unique_ptr<SrvIMUReplayMsgT> UnPackSizePrefixedSrvIMUReplayMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SrvIMUReplayMsgT>(GetSizePrefixedSrvIMUReplayMsg(buf)->UnPack(res));
}

#endif  // FLATBUFFERS_GENERATED_S006SRVIMUREPLAYMSG_H_
