// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_M100MISSION_H_
#define FLATBUFFERS_GENERATED_M100MISSION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

struct Vec3Msg;
struct Vec3MsgBuilder;
struct Vec3MsgT;

struct Vec4Msg;
struct Vec4MsgBuilder;
struct Vec4MsgT;

struct VRSceneObject;
struct VRSceneObjectBuilder;
struct VRSceneObjectT;

struct Quest;
struct QuestBuilder;
struct QuestT;

struct MissionMsg;
struct MissionMsgBuilder;
struct MissionMsgT;

struct Vec3MsgT : public ::flatbuffers::NativeTable {
  typedef Vec3Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
};

struct Vec3Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec3MsgT NativeTableType;
  typedef Vec3MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
  Vec3MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec3Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec3MsgBuilder {
  typedef Vec3Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec3Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec3Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec3Msg::VT_Z, z, 0.0f);
  }
  explicit Vec3MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec3Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec3Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f) {
  Vec3MsgBuilder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct Vec4MsgT : public ::flatbuffers::NativeTable {
  typedef Vec4Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
  float w = 0.0f;
};

struct Vec4Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec4MsgT NativeTableType;
  typedef Vec4MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8,
    VT_W = 10
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  float w() const {
    return GetField<float>(VT_W, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           VerifyField<float>(verifier, VT_W, 4) &&
           verifier.EndTable();
  }
  Vec4MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec4Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec4MsgBuilder {
  typedef Vec4Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec4Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec4Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec4Msg::VT_Z, z, 0.0f);
  }
  void add_w(float w) {
    fbb_.AddElement<float>(Vec4Msg::VT_W, w, 0.0f);
  }
  explicit Vec4MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec4Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec4Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f,
    float w = 0.0f) {
  Vec4MsgBuilder builder_(_fbb);
  builder_.add_w(w);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct VRSceneObjectT : public ::flatbuffers::NativeTable {
  typedef VRSceneObject TableType;
  std::string object_type{};
  std::string name{};
  float scale = 0.0f;
  std::unique_ptr<Vec3MsgT> position{};
  std::unique_ptr<Vec3MsgT> eul{};
  std::unique_ptr<Vec3MsgT> angvel{};
  std::unique_ptr<Vec3MsgT> linvel{};
  VRSceneObjectT() = default;
  VRSceneObjectT(const VRSceneObjectT &o);
  VRSceneObjectT(VRSceneObjectT&&) FLATBUFFERS_NOEXCEPT = default;
  VRSceneObjectT &operator=(VRSceneObjectT o) FLATBUFFERS_NOEXCEPT;
};

struct VRSceneObject FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VRSceneObjectT NativeTableType;
  typedef VRSceneObjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJECT_TYPE = 4,
    VT_NAME = 6,
    VT_SCALE = 8,
    VT_POSITION = 10,
    VT_EUL = 12,
    VT_ANGVEL = 14,
    VT_LINVEL = 16
  };
  const ::flatbuffers::String *object_type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OBJECT_TYPE);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  float scale() const {
    return GetField<float>(VT_SCALE, 0.0f);
  }
  const Vec3Msg *position() const {
    return GetPointer<const Vec3Msg *>(VT_POSITION);
  }
  const Vec3Msg *eul() const {
    return GetPointer<const Vec3Msg *>(VT_EUL);
  }
  const Vec3Msg *angvel() const {
    return GetPointer<const Vec3Msg *>(VT_ANGVEL);
  }
  const Vec3Msg *linvel() const {
    return GetPointer<const Vec3Msg *>(VT_LINVEL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_OBJECT_TYPE) &&
           verifier.VerifyString(object_type()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<float>(verifier, VT_SCALE, 4) &&
           VerifyOffset(verifier, VT_POSITION) &&
           verifier.VerifyTable(position()) &&
           VerifyOffset(verifier, VT_EUL) &&
           verifier.VerifyTable(eul()) &&
           VerifyOffset(verifier, VT_ANGVEL) &&
           verifier.VerifyTable(angvel()) &&
           VerifyOffset(verifier, VT_LINVEL) &&
           verifier.VerifyTable(linvel()) &&
           verifier.EndTable();
  }
  VRSceneObjectT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(VRSceneObjectT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<VRSceneObject> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const VRSceneObjectT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct VRSceneObjectBuilder {
  typedef VRSceneObject Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_object_type(::flatbuffers::Offset<::flatbuffers::String> object_type) {
    fbb_.AddOffset(VRSceneObject::VT_OBJECT_TYPE, object_type);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(VRSceneObject::VT_NAME, name);
  }
  void add_scale(float scale) {
    fbb_.AddElement<float>(VRSceneObject::VT_SCALE, scale, 0.0f);
  }
  void add_position(::flatbuffers::Offset<Vec3Msg> position) {
    fbb_.AddOffset(VRSceneObject::VT_POSITION, position);
  }
  void add_eul(::flatbuffers::Offset<Vec3Msg> eul) {
    fbb_.AddOffset(VRSceneObject::VT_EUL, eul);
  }
  void add_angvel(::flatbuffers::Offset<Vec3Msg> angvel) {
    fbb_.AddOffset(VRSceneObject::VT_ANGVEL, angvel);
  }
  void add_linvel(::flatbuffers::Offset<Vec3Msg> linvel) {
    fbb_.AddOffset(VRSceneObject::VT_LINVEL, linvel);
  }
  explicit VRSceneObjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VRSceneObject> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VRSceneObject>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VRSceneObject> CreateVRSceneObject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> object_type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    float scale = 0.0f,
    ::flatbuffers::Offset<Vec3Msg> position = 0,
    ::flatbuffers::Offset<Vec3Msg> eul = 0,
    ::flatbuffers::Offset<Vec3Msg> angvel = 0,
    ::flatbuffers::Offset<Vec3Msg> linvel = 0) {
  VRSceneObjectBuilder builder_(_fbb);
  builder_.add_linvel(linvel);
  builder_.add_angvel(angvel);
  builder_.add_eul(eul);
  builder_.add_position(position);
  builder_.add_scale(scale);
  builder_.add_name(name);
  builder_.add_object_type(object_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VRSceneObject> CreateVRSceneObjectDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *object_type = nullptr,
    const char *name = nullptr,
    float scale = 0.0f,
    ::flatbuffers::Offset<Vec3Msg> position = 0,
    ::flatbuffers::Offset<Vec3Msg> eul = 0,
    ::flatbuffers::Offset<Vec3Msg> angvel = 0,
    ::flatbuffers::Offset<Vec3Msg> linvel = 0) {
  auto object_type__ = object_type ? _fbb.CreateString(object_type) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return CreateVRSceneObject(
      _fbb,
      object_type__,
      name__,
      scale,
      position,
      eul,
      angvel,
      linvel);
}

::flatbuffers::Offset<VRSceneObject> CreateVRSceneObject(::flatbuffers::FlatBufferBuilder &_fbb, const VRSceneObjectT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct QuestT : public ::flatbuffers::NativeTable {
  typedef Quest TableType;
  uint32_t id = 0;
  std::string name{};
  std::string type{};
  std::unique_ptr<VRSceneObjectT> target{};
  bool is_completed = false;
  QuestT() = default;
  QuestT(const QuestT &o);
  QuestT(QuestT&&) FLATBUFFERS_NOEXCEPT = default;
  QuestT &operator=(QuestT o) FLATBUFFERS_NOEXCEPT;
};

struct Quest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef QuestT NativeTableType;
  typedef QuestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_NAME = 6,
    VT_TYPE = 8,
    VT_TARGET = 10,
    VT_IS_COMPLETED = 12
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TYPE);
  }
  const VRSceneObject *target() const {
    return GetPointer<const VRSceneObject *>(VT_TARGET);
  }
  bool is_completed() const {
    return GetField<uint8_t>(VT_IS_COMPLETED, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyString(type()) &&
           VerifyOffset(verifier, VT_TARGET) &&
           verifier.VerifyTable(target()) &&
           VerifyField<uint8_t>(verifier, VT_IS_COMPLETED, 1) &&
           verifier.EndTable();
  }
  QuestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(QuestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Quest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const QuestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct QuestBuilder {
  typedef Quest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(Quest::VT_ID, id, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Quest::VT_NAME, name);
  }
  void add_type(::flatbuffers::Offset<::flatbuffers::String> type) {
    fbb_.AddOffset(Quest::VT_TYPE, type);
  }
  void add_target(::flatbuffers::Offset<VRSceneObject> target) {
    fbb_.AddOffset(Quest::VT_TARGET, target);
  }
  void add_is_completed(bool is_completed) {
    fbb_.AddElement<uint8_t>(Quest::VT_IS_COMPLETED, static_cast<uint8_t>(is_completed), 0);
  }
  explicit QuestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Quest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Quest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Quest> CreateQuest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> type = 0,
    ::flatbuffers::Offset<VRSceneObject> target = 0,
    bool is_completed = false) {
  QuestBuilder builder_(_fbb);
  builder_.add_target(target);
  builder_.add_type(type);
  builder_.add_name(name);
  builder_.add_id(id);
  builder_.add_is_completed(is_completed);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Quest> CreateQuestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    const char *name = nullptr,
    const char *type = nullptr,
    ::flatbuffers::Offset<VRSceneObject> target = 0,
    bool is_completed = false) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto type__ = type ? _fbb.CreateString(type) : 0;
  return CreateQuest(
      _fbb,
      id,
      name__,
      type__,
      target,
      is_completed);
}

::flatbuffers::Offset<Quest> CreateQuest(::flatbuffers::FlatBufferBuilder &_fbb, const QuestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct MissionMsgT : public ::flatbuffers::NativeTable {
  typedef MissionMsg TableType;
  uint32_t id = 0;
  std::string name{};
  double timestamp = 0.0;
  bool new_mission = false;
  std::string main_scene{};
  std::vector<std::string> other_scenes{};
  std::unique_ptr<Vec3MsgT> main_camera_position{};
  std::unique_ptr<Vec3MsgT> main_camera_eul{};
  bool clear_nvr_objects = false;
  std::vector<std::unique_ptr<VRSceneObjectT>> nvr_objects{};
  bool clear_vrobots = false;
  std::vector<std::unique_ptr<VRSceneObjectT>> vrobots{};
  std::vector<std::unique_ptr<QuestT>> quests{};
  MissionMsgT() = default;
  MissionMsgT(const MissionMsgT &o);
  MissionMsgT(MissionMsgT&&) FLATBUFFERS_NOEXCEPT = default;
  MissionMsgT &operator=(MissionMsgT o) FLATBUFFERS_NOEXCEPT;
};

struct MissionMsg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MissionMsgT NativeTableType;
  typedef MissionMsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_NAME = 6,
    VT_TIMESTAMP = 8,
    VT_NEW_MISSION = 10,
    VT_MAIN_SCENE = 12,
    VT_OTHER_SCENES = 14,
    VT_MAIN_CAMERA_POSITION = 16,
    VT_MAIN_CAMERA_EUL = 18,
    VT_CLEAR_NVR_OBJECTS = 20,
    VT_NVR_OBJECTS = 22,
    VT_CLEAR_VROBOTS = 24,
    VT_VROBOTS = 26,
    VT_QUESTS = 28
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  double timestamp() const {
    return GetField<double>(VT_TIMESTAMP, 0.0);
  }
  bool new_mission() const {
    return GetField<uint8_t>(VT_NEW_MISSION, 0) != 0;
  }
  const ::flatbuffers::String *main_scene() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MAIN_SCENE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *other_scenes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_OTHER_SCENES);
  }
  const Vec3Msg *main_camera_position() const {
    return GetPointer<const Vec3Msg *>(VT_MAIN_CAMERA_POSITION);
  }
  const Vec3Msg *main_camera_eul() const {
    return GetPointer<const Vec3Msg *>(VT_MAIN_CAMERA_EUL);
  }
  bool clear_nvr_objects() const {
    return GetField<uint8_t>(VT_CLEAR_NVR_OBJECTS, 0) != 0;
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<VRSceneObject>> *nvr_objects() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<VRSceneObject>> *>(VT_NVR_OBJECTS);
  }
  bool clear_vrobots() const {
    return GetField<uint8_t>(VT_CLEAR_VROBOTS, 0) != 0;
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<VRSceneObject>> *vrobots() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<VRSceneObject>> *>(VT_VROBOTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Quest>> *quests() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Quest>> *>(VT_QUESTS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<double>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<uint8_t>(verifier, VT_NEW_MISSION, 1) &&
           VerifyOffset(verifier, VT_MAIN_SCENE) &&
           verifier.VerifyString(main_scene()) &&
           VerifyOffset(verifier, VT_OTHER_SCENES) &&
           verifier.VerifyVector(other_scenes()) &&
           verifier.VerifyVectorOfStrings(other_scenes()) &&
           VerifyOffset(verifier, VT_MAIN_CAMERA_POSITION) &&
           verifier.VerifyTable(main_camera_position()) &&
           VerifyOffset(verifier, VT_MAIN_CAMERA_EUL) &&
           verifier.VerifyTable(main_camera_eul()) &&
           VerifyField<uint8_t>(verifier, VT_CLEAR_NVR_OBJECTS, 1) &&
           VerifyOffset(verifier, VT_NVR_OBJECTS) &&
           verifier.VerifyVector(nvr_objects()) &&
           verifier.VerifyVectorOfTables(nvr_objects()) &&
           VerifyField<uint8_t>(verifier, VT_CLEAR_VROBOTS, 1) &&
           VerifyOffset(verifier, VT_VROBOTS) &&
           verifier.VerifyVector(vrobots()) &&
           verifier.VerifyVectorOfTables(vrobots()) &&
           VerifyOffset(verifier, VT_QUESTS) &&
           verifier.VerifyVector(quests()) &&
           verifier.VerifyVectorOfTables(quests()) &&
           verifier.EndTable();
  }
  MissionMsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MissionMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<MissionMsg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MissionMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MissionMsgBuilder {
  typedef MissionMsg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(MissionMsg::VT_ID, id, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(MissionMsg::VT_NAME, name);
  }
  void add_timestamp(double timestamp) {
    fbb_.AddElement<double>(MissionMsg::VT_TIMESTAMP, timestamp, 0.0);
  }
  void add_new_mission(bool new_mission) {
    fbb_.AddElement<uint8_t>(MissionMsg::VT_NEW_MISSION, static_cast<uint8_t>(new_mission), 0);
  }
  void add_main_scene(::flatbuffers::Offset<::flatbuffers::String> main_scene) {
    fbb_.AddOffset(MissionMsg::VT_MAIN_SCENE, main_scene);
  }
  void add_other_scenes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> other_scenes) {
    fbb_.AddOffset(MissionMsg::VT_OTHER_SCENES, other_scenes);
  }
  void add_main_camera_position(::flatbuffers::Offset<Vec3Msg> main_camera_position) {
    fbb_.AddOffset(MissionMsg::VT_MAIN_CAMERA_POSITION, main_camera_position);
  }
  void add_main_camera_eul(::flatbuffers::Offset<Vec3Msg> main_camera_eul) {
    fbb_.AddOffset(MissionMsg::VT_MAIN_CAMERA_EUL, main_camera_eul);
  }
  void add_clear_nvr_objects(bool clear_nvr_objects) {
    fbb_.AddElement<uint8_t>(MissionMsg::VT_CLEAR_NVR_OBJECTS, static_cast<uint8_t>(clear_nvr_objects), 0);
  }
  void add_nvr_objects(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<VRSceneObject>>> nvr_objects) {
    fbb_.AddOffset(MissionMsg::VT_NVR_OBJECTS, nvr_objects);
  }
  void add_clear_vrobots(bool clear_vrobots) {
    fbb_.AddElement<uint8_t>(MissionMsg::VT_CLEAR_VROBOTS, static_cast<uint8_t>(clear_vrobots), 0);
  }
  void add_vrobots(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<VRSceneObject>>> vrobots) {
    fbb_.AddOffset(MissionMsg::VT_VROBOTS, vrobots);
  }
  void add_quests(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Quest>>> quests) {
    fbb_.AddOffset(MissionMsg::VT_QUESTS, quests);
  }
  explicit MissionMsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MissionMsg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MissionMsg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MissionMsg> CreateMissionMsg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    double timestamp = 0.0,
    bool new_mission = false,
    ::flatbuffers::Offset<::flatbuffers::String> main_scene = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> other_scenes = 0,
    ::flatbuffers::Offset<Vec3Msg> main_camera_position = 0,
    ::flatbuffers::Offset<Vec3Msg> main_camera_eul = 0,
    bool clear_nvr_objects = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<VRSceneObject>>> nvr_objects = 0,
    bool clear_vrobots = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<VRSceneObject>>> vrobots = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Quest>>> quests = 0) {
  MissionMsgBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_quests(quests);
  builder_.add_vrobots(vrobots);
  builder_.add_nvr_objects(nvr_objects);
  builder_.add_main_camera_eul(main_camera_eul);
  builder_.add_main_camera_position(main_camera_position);
  builder_.add_other_scenes(other_scenes);
  builder_.add_main_scene(main_scene);
  builder_.add_name(name);
  builder_.add_id(id);
  builder_.add_clear_vrobots(clear_vrobots);
  builder_.add_clear_nvr_objects(clear_nvr_objects);
  builder_.add_new_mission(new_mission);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MissionMsg> CreateMissionMsgDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    const char *name = nullptr,
    double timestamp = 0.0,
    bool new_mission = false,
    const char *main_scene = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *other_scenes = nullptr,
    ::flatbuffers::Offset<Vec3Msg> main_camera_position = 0,
    ::flatbuffers::Offset<Vec3Msg> main_camera_eul = 0,
    bool clear_nvr_objects = false,
    const std::vector<::flatbuffers::Offset<VRSceneObject>> *nvr_objects = nullptr,
    bool clear_vrobots = false,
    const std::vector<::flatbuffers::Offset<VRSceneObject>> *vrobots = nullptr,
    const std::vector<::flatbuffers::Offset<Quest>> *quests = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto main_scene__ = main_scene ? _fbb.CreateString(main_scene) : 0;
  auto other_scenes__ = other_scenes ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*other_scenes) : 0;
  auto nvr_objects__ = nvr_objects ? _fbb.CreateVector<::flatbuffers::Offset<VRSceneObject>>(*nvr_objects) : 0;
  auto vrobots__ = vrobots ? _fbb.CreateVector<::flatbuffers::Offset<VRSceneObject>>(*vrobots) : 0;
  auto quests__ = quests ? _fbb.CreateVector<::flatbuffers::Offset<Quest>>(*quests) : 0;
  return CreateMissionMsg(
      _fbb,
      id,
      name__,
      timestamp,
      new_mission,
      main_scene__,
      other_scenes__,
      main_camera_position,
      main_camera_eul,
      clear_nvr_objects,
      nvr_objects__,
      clear_vrobots,
      vrobots__,
      quests__);
}

::flatbuffers::Offset<MissionMsg> CreateMissionMsg(::flatbuffers::FlatBufferBuilder &_fbb, const MissionMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline Vec3MsgT *Vec3Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec3MsgT>(new Vec3MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec3Msg::UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
}

inline ::flatbuffers::Offset<Vec3Msg> Vec3Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec3Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec3MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  return CreateVec3Msg(
      _fbb,
      _x,
      _y,
      _z);
}

inline Vec4MsgT *Vec4Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec4MsgT>(new Vec4MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec4Msg::UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
  { auto _e = w(); _o->w = _e; }
}

inline ::flatbuffers::Offset<Vec4Msg> Vec4Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec4Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec4MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  auto _w = _o->w;
  return CreateVec4Msg(
      _fbb,
      _x,
      _y,
      _z,
      _w);
}

inline VRSceneObjectT::VRSceneObjectT(const VRSceneObjectT &o)
      : object_type(o.object_type),
        name(o.name),
        scale(o.scale),
        position((o.position) ? new Vec3MsgT(*o.position) : nullptr),
        eul((o.eul) ? new Vec3MsgT(*o.eul) : nullptr),
        angvel((o.angvel) ? new Vec3MsgT(*o.angvel) : nullptr),
        linvel((o.linvel) ? new Vec3MsgT(*o.linvel) : nullptr) {
}

inline VRSceneObjectT &VRSceneObjectT::operator=(VRSceneObjectT o) FLATBUFFERS_NOEXCEPT {
  std::swap(object_type, o.object_type);
  std::swap(name, o.name);
  std::swap(scale, o.scale);
  std::swap(position, o.position);
  std::swap(eul, o.eul);
  std::swap(angvel, o.angvel);
  std::swap(linvel, o.linvel);
  return *this;
}

inline VRSceneObjectT *VRSceneObject::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<VRSceneObjectT>(new VRSceneObjectT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void VRSceneObject::UnPackTo(VRSceneObjectT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = object_type(); if (_e) _o->object_type = _e->str(); }
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = scale(); _o->scale = _e; }
  { auto _e = position(); if (_e) { if(_o->position) { _e->UnPackTo(_o->position.get(), _resolver); } else { _o->position = std::unique_ptr<Vec3MsgT>(_e->UnPack(_resolver)); } } else if (_o->position) { _o->position.reset(); } }
  { auto _e = eul(); if (_e) { if(_o->eul) { _e->UnPackTo(_o->eul.get(), _resolver); } else { _o->eul = std::unique_ptr<Vec3MsgT>(_e->UnPack(_resolver)); } } else if (_o->eul) { _o->eul.reset(); } }
  { auto _e = angvel(); if (_e) { if(_o->angvel) { _e->UnPackTo(_o->angvel.get(), _resolver); } else { _o->angvel = std::unique_ptr<Vec3MsgT>(_e->UnPack(_resolver)); } } else if (_o->angvel) { _o->angvel.reset(); } }
  { auto _e = linvel(); if (_e) { if(_o->linvel) { _e->UnPackTo(_o->linvel.get(), _resolver); } else { _o->linvel = std::unique_ptr<Vec3MsgT>(_e->UnPack(_resolver)); } } else if (_o->linvel) { _o->linvel.reset(); } }
}

inline ::flatbuffers::Offset<VRSceneObject> VRSceneObject::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const VRSceneObjectT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVRSceneObject(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<VRSceneObject> CreateVRSceneObject(::flatbuffers::FlatBufferBuilder &_fbb, const VRSceneObjectT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const VRSceneObjectT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _object_type = _o->object_type.empty() ? 0 : _fbb.CreateString(_o->object_type);
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _scale = _o->scale;
  auto _position = _o->position ? CreateVec3Msg(_fbb, _o->position.get(), _rehasher) : 0;
  auto _eul = _o->eul ? CreateVec3Msg(_fbb, _o->eul.get(), _rehasher) : 0;
  auto _angvel = _o->angvel ? CreateVec3Msg(_fbb, _o->angvel.get(), _rehasher) : 0;
  auto _linvel = _o->linvel ? CreateVec3Msg(_fbb, _o->linvel.get(), _rehasher) : 0;
  return CreateVRSceneObject(
      _fbb,
      _object_type,
      _name,
      _scale,
      _position,
      _eul,
      _angvel,
      _linvel);
}

inline QuestT::QuestT(const QuestT &o)
      : id(o.id),
        name(o.name),
        type(o.type),
        target((o.target) ? new VRSceneObjectT(*o.target) : nullptr),
        is_completed(o.is_completed) {
}

inline QuestT &QuestT::operator=(QuestT o) FLATBUFFERS_NOEXCEPT {
  std::swap(id, o.id);
  std::swap(name, o.name);
  std::swap(type, o.type);
  std::swap(target, o.target);
  std::swap(is_completed, o.is_completed);
  return *this;
}

inline QuestT *Quest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<QuestT>(new QuestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Quest::UnPackTo(QuestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = id(); _o->id = _e; }
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = type(); if (_e) _o->type = _e->str(); }
  { auto _e = target(); if (_e) { if(_o->target) { _e->UnPackTo(_o->target.get(), _resolver); } else { _o->target = std::unique_ptr<VRSceneObjectT>(_e->UnPack(_resolver)); } } else if (_o->target) { _o->target.reset(); } }
  { auto _e = is_completed(); _o->is_completed = _e; }
}

inline ::flatbuffers::Offset<Quest> Quest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const QuestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateQuest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Quest> CreateQuest(::flatbuffers::FlatBufferBuilder &_fbb, const QuestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const QuestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _id = _o->id;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _type = _o->type.empty() ? 0 : _fbb.CreateString(_o->type);
  auto _target = _o->target ? CreateVRSceneObject(_fbb, _o->target.get(), _rehasher) : 0;
  auto _is_completed = _o->is_completed;
  return CreateQuest(
      _fbb,
      _id,
      _name,
      _type,
      _target,
      _is_completed);
}

inline MissionMsgT::MissionMsgT(const MissionMsgT &o)
      : id(o.id),
        name(o.name),
        timestamp(o.timestamp),
        new_mission(o.new_mission),
        main_scene(o.main_scene),
        other_scenes(o.other_scenes),
        main_camera_position((o.main_camera_position) ? new Vec3MsgT(*o.main_camera_position) : nullptr),
        main_camera_eul((o.main_camera_eul) ? new Vec3MsgT(*o.main_camera_eul) : nullptr),
        clear_nvr_objects(o.clear_nvr_objects),
        clear_vrobots(o.clear_vrobots) {
  nvr_objects.reserve(o.nvr_objects.size());
  for (const auto &nvr_objects_ : o.nvr_objects) { nvr_objects.emplace_back((nvr_objects_) ? new VRSceneObjectT(*nvr_objects_) : nullptr); }
  vrobots.reserve(o.vrobots.size());
  for (const auto &vrobots_ : o.vrobots) { vrobots.emplace_back((vrobots_) ? new VRSceneObjectT(*vrobots_) : nullptr); }
  quests.reserve(o.quests.size());
  for (const auto &quests_ : o.quests) { quests.emplace_back((quests_) ? new QuestT(*quests_) : nullptr); }
}

inline MissionMsgT &MissionMsgT::operator=(MissionMsgT o) FLATBUFFERS_NOEXCEPT {
  std::swap(id, o.id);
  std::swap(name, o.name);
  std::swap(timestamp, o.timestamp);
  std::swap(new_mission, o.new_mission);
  std::swap(main_scene, o.main_scene);
  std::swap(other_scenes, o.other_scenes);
  std::swap(main_camera_position, o.main_camera_position);
  std::swap(main_camera_eul, o.main_camera_eul);
  std::swap(clear_nvr_objects, o.clear_nvr_objects);
  std::swap(nvr_objects, o.nvr_objects);
  std::swap(clear_vrobots, o.clear_vrobots);
  std::swap(vrobots, o.vrobots);
  std::swap(quests, o.quests);
  return *this;
}

inline MissionMsgT *MissionMsg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<MissionMsgT>(new MissionMsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void MissionMsg::UnPackTo(MissionMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = id(); _o->id = _e; }
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = timestamp(); _o->timestamp = _e; }
  { auto _e = new_mission(); _o->new_mission = _e; }
  { auto _e = main_scene(); if (_e) _o->main_scene = _e->str(); }
  { auto _e = other_scenes(); if (_e) { _o->other_scenes.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->other_scenes[_i] = _e->Get(_i)->str(); } } else { _o->other_scenes.resize(0); } }
  { auto _e = main_camera_position(); if (_e) { if(_o->main_camera_position) { _e->UnPackTo(_o->main_camera_position.get(), _resolver); } else { _o->main_camera_position = std::unique_ptr<Vec3MsgT>(_e->UnPack(_resolver)); } } else if (_o->main_camera_position) { _o->main_camera_position.reset(); } }
  { auto _e = main_camera_eul(); if (_e) { if(_o->main_camera_eul) { _e->UnPackTo(_o->main_camera_eul.get(), _resolver); } else { _o->main_camera_eul = std::unique_ptr<Vec3MsgT>(_e->UnPack(_resolver)); } } else if (_o->main_camera_eul) { _o->main_camera_eul.reset(); } }
  { auto _e = clear_nvr_objects(); _o->clear_nvr_objects = _e; }
  { auto _e = nvr_objects(); if (_e) { _o->nvr_objects.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->nvr_objects[_i]) { _e->Get(_i)->UnPackTo(_o->nvr_objects[_i].get(), _resolver); } else { _o->nvr_objects[_i] = std::unique_ptr<VRSceneObjectT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->nvr_objects.resize(0); } }
  { auto _e = clear_vrobots(); _o->clear_vrobots = _e; }
  { auto _e = vrobots(); if (_e) { _o->vrobots.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->vrobots[_i]) { _e->Get(_i)->UnPackTo(_o->vrobots[_i].get(), _resolver); } else { _o->vrobots[_i] = std::unique_ptr<VRSceneObjectT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->vrobots.resize(0); } }
  { auto _e = quests(); if (_e) { _o->quests.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->quests[_i]) { _e->Get(_i)->UnPackTo(_o->quests[_i].get(), _resolver); } else { _o->quests[_i] = std::unique_ptr<QuestT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->quests.resize(0); } }
}

inline ::flatbuffers::Offset<MissionMsg> MissionMsg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MissionMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateMissionMsg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<MissionMsg> CreateMissionMsg(::flatbuffers::FlatBufferBuilder &_fbb, const MissionMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const MissionMsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _id = _o->id;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _timestamp = _o->timestamp;
  auto _new_mission = _o->new_mission;
  auto _main_scene = _o->main_scene.empty() ? 0 : _fbb.CreateString(_o->main_scene);
  auto _other_scenes = _o->other_scenes.size() ? _fbb.CreateVectorOfStrings(_o->other_scenes) : 0;
  auto _main_camera_position = _o->main_camera_position ? CreateVec3Msg(_fbb, _o->main_camera_position.get(), _rehasher) : 0;
  auto _main_camera_eul = _o->main_camera_eul ? CreateVec3Msg(_fbb, _o->main_camera_eul.get(), _rehasher) : 0;
  auto _clear_nvr_objects = _o->clear_nvr_objects;
  auto _nvr_objects = _o->nvr_objects.size() ? _fbb.CreateVector<::flatbuffers::Offset<VRSceneObject>> (_o->nvr_objects.size(), [](size_t i, _VectorArgs *__va) { return CreateVRSceneObject(*__va->__fbb, __va->__o->nvr_objects[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _clear_vrobots = _o->clear_vrobots;
  auto _vrobots = _o->vrobots.size() ? _fbb.CreateVector<::flatbuffers::Offset<VRSceneObject>> (_o->vrobots.size(), [](size_t i, _VectorArgs *__va) { return CreateVRSceneObject(*__va->__fbb, __va->__o->vrobots[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _quests = _o->quests.size() ? _fbb.CreateVector<::flatbuffers::Offset<Quest>> (_o->quests.size(), [](size_t i, _VectorArgs *__va) { return CreateQuest(*__va->__fbb, __va->__o->quests[i].get(), __va->__rehasher); }, &_va ) : 0;
  return CreateMissionMsg(
      _fbb,
      _id,
      _name,
      _timestamp,
      _new_mission,
      _main_scene,
      _other_scenes,
      _main_camera_position,
      _main_camera_eul,
      _clear_nvr_objects,
      _nvr_objects,
      _clear_vrobots,
      _vrobots,
      _quests);
}

inline const MissionMsg *GetMissionMsg(const void *buf) {
  return ::flatbuffers::GetRoot<MissionMsg>(buf);
}

inline const MissionMsg *GetSizePrefixedMissionMsg(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<MissionMsg>(buf);
}

inline const char *MissionMsgIdentifier() {
  return "M100";
}

inline bool MissionMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, MissionMsgIdentifier());
}

inline bool SizePrefixedMissionMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, MissionMsgIdentifier(), true);
}

inline bool VerifyMissionMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<MissionMsg>(MissionMsgIdentifier());
}

inline bool VerifySizePrefixedMissionMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<MissionMsg>(MissionMsgIdentifier());
}

inline void FinishMissionMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MissionMsg> root) {
  fbb.Finish(root, MissionMsgIdentifier());
}

inline void FinishSizePrefixedMissionMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MissionMsg> root) {
  fbb.FinishSizePrefixed(root, MissionMsgIdentifier());
}

inline std::unique_ptr<MissionMsgT> UnPackMissionMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<MissionMsgT>(GetMissionMsg(buf)->UnPack(res));
}

inline std::unique_ptr<MissionMsgT> UnPackSizePrefixedMissionMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<MissionMsgT>(GetSizePrefixedMissionMsg(buf)->UnPack(res));
}

#endif  // FLATBUFFERS_GENERATED_M100MISSION_H_
