// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_S005SRVDRONE1DPIDMSG_H_
#define FLATBUFFERS_GENERATED_S005SRVDRONE1DPIDMSG_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

struct Vec3Msg;
struct Vec3MsgBuilder;
struct Vec3MsgT;

struct Vec4Msg;
struct Vec4MsgBuilder;
struct Vec4MsgT;

struct SrvDrone1DPIDMsg;
struct SrvDrone1DPIDMsgBuilder;
struct SrvDrone1DPIDMsgT;

struct Vec3MsgT : public ::flatbuffers::NativeTable {
  typedef Vec3Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
};

struct Vec3Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec3MsgT NativeTableType;
  typedef Vec3MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
  Vec3MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec3Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec3MsgBuilder {
  typedef Vec3Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec3Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec3Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec3Msg::VT_Z, z, 0.0f);
  }
  explicit Vec3MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec3Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec3Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f) {
  Vec3MsgBuilder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct Vec4MsgT : public ::flatbuffers::NativeTable {
  typedef Vec4Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
  float w = 0.0f;
};

struct Vec4Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec4MsgT NativeTableType;
  typedef Vec4MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8,
    VT_W = 10
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  float w() const {
    return GetField<float>(VT_W, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           VerifyField<float>(verifier, VT_W, 4) &&
           verifier.EndTable();
  }
  Vec4MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec4Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec4MsgBuilder {
  typedef Vec4Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec4Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec4Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec4Msg::VT_Z, z, 0.0f);
  }
  void add_w(float w) {
    fbb_.AddElement<float>(Vec4Msg::VT_W, w, 0.0f);
  }
  explicit Vec4MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec4Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec4Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f,
    float w = 0.0f) {
  Vec4MsgBuilder builder_(_fbb);
  builder_.add_w(w);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SrvDrone1DPIDMsgT : public ::flatbuffers::NativeTable {
  typedef SrvDrone1DPIDMsg TableType;
  double timestamp = 0.0;
  std::string name{};
  uint32_t sys_id = 0;
  uint32_t req_src_id = 0;
  bool set_pid_on = false;
  bool set_kp = false;
  bool set_ki = false;
  bool set_kd = false;
  bool set_setpoint = false;
  bool pid_on = false;
  float kp = 0.0f;
  float ki = 0.0f;
  float kd = 0.0f;
  float setpoint = 0.0f;
  bool set_left_arm_length = false;
  float left_arm_length = 0.0f;
  bool set_right_arm_length = false;
  float right_arm_length = 0.0f;
  bool set_uint_mass = false;
  float uint_mass = 0.0f;
};

struct SrvDrone1DPIDMsg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SrvDrone1DPIDMsgT NativeTableType;
  typedef SrvDrone1DPIDMsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_NAME = 6,
    VT_SYS_ID = 8,
    VT_REQ_SRC_ID = 10,
    VT_SET_PID_ON = 12,
    VT_SET_KP = 14,
    VT_SET_KI = 16,
    VT_SET_KD = 18,
    VT_SET_SETPOINT = 20,
    VT_PID_ON = 22,
    VT_KP = 24,
    VT_KI = 26,
    VT_KD = 28,
    VT_SETPOINT = 30,
    VT_SET_LEFT_ARM_LENGTH = 32,
    VT_LEFT_ARM_LENGTH = 34,
    VT_SET_RIGHT_ARM_LENGTH = 36,
    VT_RIGHT_ARM_LENGTH = 38,
    VT_SET_UINT_MASS = 40,
    VT_UINT_MASS = 42
  };
  double timestamp() const {
    return GetField<double>(VT_TIMESTAMP, 0.0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint32_t sys_id() const {
    return GetField<uint32_t>(VT_SYS_ID, 0);
  }
  uint32_t req_src_id() const {
    return GetField<uint32_t>(VT_REQ_SRC_ID, 0);
  }
  bool set_pid_on() const {
    return GetField<uint8_t>(VT_SET_PID_ON, 0) != 0;
  }
  bool set_kp() const {
    return GetField<uint8_t>(VT_SET_KP, 0) != 0;
  }
  bool set_ki() const {
    return GetField<uint8_t>(VT_SET_KI, 0) != 0;
  }
  bool set_kd() const {
    return GetField<uint8_t>(VT_SET_KD, 0) != 0;
  }
  bool set_setpoint() const {
    return GetField<uint8_t>(VT_SET_SETPOINT, 0) != 0;
  }
  bool pid_on() const {
    return GetField<uint8_t>(VT_PID_ON, 0) != 0;
  }
  float kp() const {
    return GetField<float>(VT_KP, 0.0f);
  }
  float ki() const {
    return GetField<float>(VT_KI, 0.0f);
  }
  float kd() const {
    return GetField<float>(VT_KD, 0.0f);
  }
  float setpoint() const {
    return GetField<float>(VT_SETPOINT, 0.0f);
  }
  bool set_left_arm_length() const {
    return GetField<uint8_t>(VT_SET_LEFT_ARM_LENGTH, 0) != 0;
  }
  float left_arm_length() const {
    return GetField<float>(VT_LEFT_ARM_LENGTH, 0.0f);
  }
  bool set_right_arm_length() const {
    return GetField<uint8_t>(VT_SET_RIGHT_ARM_LENGTH, 0) != 0;
  }
  float right_arm_length() const {
    return GetField<float>(VT_RIGHT_ARM_LENGTH, 0.0f);
  }
  bool set_uint_mass() const {
    return GetField<uint8_t>(VT_SET_UINT_MASS, 0) != 0;
  }
  float uint_mass() const {
    return GetField<float>(VT_UINT_MASS, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_TIMESTAMP, 8) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint32_t>(verifier, VT_SYS_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_REQ_SRC_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_SET_PID_ON, 1) &&
           VerifyField<uint8_t>(verifier, VT_SET_KP, 1) &&
           VerifyField<uint8_t>(verifier, VT_SET_KI, 1) &&
           VerifyField<uint8_t>(verifier, VT_SET_KD, 1) &&
           VerifyField<uint8_t>(verifier, VT_SET_SETPOINT, 1) &&
           VerifyField<uint8_t>(verifier, VT_PID_ON, 1) &&
           VerifyField<float>(verifier, VT_KP, 4) &&
           VerifyField<float>(verifier, VT_KI, 4) &&
           VerifyField<float>(verifier, VT_KD, 4) &&
           VerifyField<float>(verifier, VT_SETPOINT, 4) &&
           VerifyField<uint8_t>(verifier, VT_SET_LEFT_ARM_LENGTH, 1) &&
           VerifyField<float>(verifier, VT_LEFT_ARM_LENGTH, 4) &&
           VerifyField<uint8_t>(verifier, VT_SET_RIGHT_ARM_LENGTH, 1) &&
           VerifyField<float>(verifier, VT_RIGHT_ARM_LENGTH, 4) &&
           VerifyField<uint8_t>(verifier, VT_SET_UINT_MASS, 1) &&
           VerifyField<float>(verifier, VT_UINT_MASS, 4) &&
           verifier.EndTable();
  }
  SrvDrone1DPIDMsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SrvDrone1DPIDMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SrvDrone1DPIDMsg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SrvDrone1DPIDMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SrvDrone1DPIDMsgBuilder {
  typedef SrvDrone1DPIDMsg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(double timestamp) {
    fbb_.AddElement<double>(SrvDrone1DPIDMsg::VT_TIMESTAMP, timestamp, 0.0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(SrvDrone1DPIDMsg::VT_NAME, name);
  }
  void add_sys_id(uint32_t sys_id) {
    fbb_.AddElement<uint32_t>(SrvDrone1DPIDMsg::VT_SYS_ID, sys_id, 0);
  }
  void add_req_src_id(uint32_t req_src_id) {
    fbb_.AddElement<uint32_t>(SrvDrone1DPIDMsg::VT_REQ_SRC_ID, req_src_id, 0);
  }
  void add_set_pid_on(bool set_pid_on) {
    fbb_.AddElement<uint8_t>(SrvDrone1DPIDMsg::VT_SET_PID_ON, static_cast<uint8_t>(set_pid_on), 0);
  }
  void add_set_kp(bool set_kp) {
    fbb_.AddElement<uint8_t>(SrvDrone1DPIDMsg::VT_SET_KP, static_cast<uint8_t>(set_kp), 0);
  }
  void add_set_ki(bool set_ki) {
    fbb_.AddElement<uint8_t>(SrvDrone1DPIDMsg::VT_SET_KI, static_cast<uint8_t>(set_ki), 0);
  }
  void add_set_kd(bool set_kd) {
    fbb_.AddElement<uint8_t>(SrvDrone1DPIDMsg::VT_SET_KD, static_cast<uint8_t>(set_kd), 0);
  }
  void add_set_setpoint(bool set_setpoint) {
    fbb_.AddElement<uint8_t>(SrvDrone1DPIDMsg::VT_SET_SETPOINT, static_cast<uint8_t>(set_setpoint), 0);
  }
  void add_pid_on(bool pid_on) {
    fbb_.AddElement<uint8_t>(SrvDrone1DPIDMsg::VT_PID_ON, static_cast<uint8_t>(pid_on), 0);
  }
  void add_kp(float kp) {
    fbb_.AddElement<float>(SrvDrone1DPIDMsg::VT_KP, kp, 0.0f);
  }
  void add_ki(float ki) {
    fbb_.AddElement<float>(SrvDrone1DPIDMsg::VT_KI, ki, 0.0f);
  }
  void add_kd(float kd) {
    fbb_.AddElement<float>(SrvDrone1DPIDMsg::VT_KD, kd, 0.0f);
  }
  void add_setpoint(float setpoint) {
    fbb_.AddElement<float>(SrvDrone1DPIDMsg::VT_SETPOINT, setpoint, 0.0f);
  }
  void add_set_left_arm_length(bool set_left_arm_length) {
    fbb_.AddElement<uint8_t>(SrvDrone1DPIDMsg::VT_SET_LEFT_ARM_LENGTH, static_cast<uint8_t>(set_left_arm_length), 0);
  }
  void add_left_arm_length(float left_arm_length) {
    fbb_.AddElement<float>(SrvDrone1DPIDMsg::VT_LEFT_ARM_LENGTH, left_arm_length, 0.0f);
  }
  void add_set_right_arm_length(bool set_right_arm_length) {
    fbb_.AddElement<uint8_t>(SrvDrone1DPIDMsg::VT_SET_RIGHT_ARM_LENGTH, static_cast<uint8_t>(set_right_arm_length), 0);
  }
  void add_right_arm_length(float right_arm_length) {
    fbb_.AddElement<float>(SrvDrone1DPIDMsg::VT_RIGHT_ARM_LENGTH, right_arm_length, 0.0f);
  }
  void add_set_uint_mass(bool set_uint_mass) {
    fbb_.AddElement<uint8_t>(SrvDrone1DPIDMsg::VT_SET_UINT_MASS, static_cast<uint8_t>(set_uint_mass), 0);
  }
  void add_uint_mass(float uint_mass) {
    fbb_.AddElement<float>(SrvDrone1DPIDMsg::VT_UINT_MASS, uint_mass, 0.0f);
  }
  explicit SrvDrone1DPIDMsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SrvDrone1DPIDMsg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SrvDrone1DPIDMsg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SrvDrone1DPIDMsg> CreateSrvDrone1DPIDMsg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double timestamp = 0.0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint32_t sys_id = 0,
    uint32_t req_src_id = 0,
    bool set_pid_on = false,
    bool set_kp = false,
    bool set_ki = false,
    bool set_kd = false,
    bool set_setpoint = false,
    bool pid_on = false,
    float kp = 0.0f,
    float ki = 0.0f,
    float kd = 0.0f,
    float setpoint = 0.0f,
    bool set_left_arm_length = false,
    float left_arm_length = 0.0f,
    bool set_right_arm_length = false,
    float right_arm_length = 0.0f,
    bool set_uint_mass = false,
    float uint_mass = 0.0f) {
  SrvDrone1DPIDMsgBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_uint_mass(uint_mass);
  builder_.add_right_arm_length(right_arm_length);
  builder_.add_left_arm_length(left_arm_length);
  builder_.add_setpoint(setpoint);
  builder_.add_kd(kd);
  builder_.add_ki(ki);
  builder_.add_kp(kp);
  builder_.add_req_src_id(req_src_id);
  builder_.add_sys_id(sys_id);
  builder_.add_name(name);
  builder_.add_set_uint_mass(set_uint_mass);
  builder_.add_set_right_arm_length(set_right_arm_length);
  builder_.add_set_left_arm_length(set_left_arm_length);
  builder_.add_pid_on(pid_on);
  builder_.add_set_setpoint(set_setpoint);
  builder_.add_set_kd(set_kd);
  builder_.add_set_ki(set_ki);
  builder_.add_set_kp(set_kp);
  builder_.add_set_pid_on(set_pid_on);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SrvDrone1DPIDMsg> CreateSrvDrone1DPIDMsgDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double timestamp = 0.0,
    const char *name = nullptr,
    uint32_t sys_id = 0,
    uint32_t req_src_id = 0,
    bool set_pid_on = false,
    bool set_kp = false,
    bool set_ki = false,
    bool set_kd = false,
    bool set_setpoint = false,
    bool pid_on = false,
    float kp = 0.0f,
    float ki = 0.0f,
    float kd = 0.0f,
    float setpoint = 0.0f,
    bool set_left_arm_length = false,
    float left_arm_length = 0.0f,
    bool set_right_arm_length = false,
    float right_arm_length = 0.0f,
    bool set_uint_mass = false,
    float uint_mass = 0.0f) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return CreateSrvDrone1DPIDMsg(
      _fbb,
      timestamp,
      name__,
      sys_id,
      req_src_id,
      set_pid_on,
      set_kp,
      set_ki,
      set_kd,
      set_setpoint,
      pid_on,
      kp,
      ki,
      kd,
      setpoint,
      set_left_arm_length,
      left_arm_length,
      set_right_arm_length,
      right_arm_length,
      set_uint_mass,
      uint_mass);
}

::flatbuffers::Offset<SrvDrone1DPIDMsg> CreateSrvDrone1DPIDMsg(::flatbuffers::FlatBufferBuilder &_fbb, const SrvDrone1DPIDMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline Vec3MsgT *Vec3Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec3MsgT>(new Vec3MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec3Msg::UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
}

inline ::flatbuffers::Offset<Vec3Msg> Vec3Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec3Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec3MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  return CreateVec3Msg(
      _fbb,
      _x,
      _y,
      _z);
}

inline Vec4MsgT *Vec4Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec4MsgT>(new Vec4MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec4Msg::UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
  { auto _e = w(); _o->w = _e; }
}

inline ::flatbuffers::Offset<Vec4Msg> Vec4Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec4Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec4MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  auto _w = _o->w;
  return CreateVec4Msg(
      _fbb,
      _x,
      _y,
      _z,
      _w);
}

inline SrvDrone1DPIDMsgT *SrvDrone1DPIDMsg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SrvDrone1DPIDMsgT>(new SrvDrone1DPIDMsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SrvDrone1DPIDMsg::UnPackTo(SrvDrone1DPIDMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = timestamp(); _o->timestamp = _e; }
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = sys_id(); _o->sys_id = _e; }
  { auto _e = req_src_id(); _o->req_src_id = _e; }
  { auto _e = set_pid_on(); _o->set_pid_on = _e; }
  { auto _e = set_kp(); _o->set_kp = _e; }
  { auto _e = set_ki(); _o->set_ki = _e; }
  { auto _e = set_kd(); _o->set_kd = _e; }
  { auto _e = set_setpoint(); _o->set_setpoint = _e; }
  { auto _e = pid_on(); _o->pid_on = _e; }
  { auto _e = kp(); _o->kp = _e; }
  { auto _e = ki(); _o->ki = _e; }
  { auto _e = kd(); _o->kd = _e; }
  { auto _e = setpoint(); _o->setpoint = _e; }
  { auto _e = set_left_arm_length(); _o->set_left_arm_length = _e; }
  { auto _e = left_arm_length(); _o->left_arm_length = _e; }
  { auto _e = set_right_arm_length(); _o->set_right_arm_length = _e; }
  { auto _e = right_arm_length(); _o->right_arm_length = _e; }
  { auto _e = set_uint_mass(); _o->set_uint_mass = _e; }
  { auto _e = uint_mass(); _o->uint_mass = _e; }
}

inline ::flatbuffers::Offset<SrvDrone1DPIDMsg> SrvDrone1DPIDMsg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SrvDrone1DPIDMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSrvDrone1DPIDMsg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SrvDrone1DPIDMsg> CreateSrvDrone1DPIDMsg(::flatbuffers::FlatBufferBuilder &_fbb, const SrvDrone1DPIDMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SrvDrone1DPIDMsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _timestamp = _o->timestamp;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _sys_id = _o->sys_id;
  auto _req_src_id = _o->req_src_id;
  auto _set_pid_on = _o->set_pid_on;
  auto _set_kp = _o->set_kp;
  auto _set_ki = _o->set_ki;
  auto _set_kd = _o->set_kd;
  auto _set_setpoint = _o->set_setpoint;
  auto _pid_on = _o->pid_on;
  auto _kp = _o->kp;
  auto _ki = _o->ki;
  auto _kd = _o->kd;
  auto _setpoint = _o->setpoint;
  auto _set_left_arm_length = _o->set_left_arm_length;
  auto _left_arm_length = _o->left_arm_length;
  auto _set_right_arm_length = _o->set_right_arm_length;
  auto _right_arm_length = _o->right_arm_length;
  auto _set_uint_mass = _o->set_uint_mass;
  auto _uint_mass = _o->uint_mass;
  return CreateSrvDrone1DPIDMsg(
      _fbb,
      _timestamp,
      _name,
      _sys_id,
      _req_src_id,
      _set_pid_on,
      _set_kp,
      _set_ki,
      _set_kd,
      _set_setpoint,
      _pid_on,
      _kp,
      _ki,
      _kd,
      _setpoint,
      _set_left_arm_length,
      _left_arm_length,
      _set_right_arm_length,
      _right_arm_length,
      _set_uint_mass,
      _uint_mass);
}

inline const SrvDrone1DPIDMsg *GetSrvDrone1DPIDMsg(const void *buf) {
  return ::flatbuffers::GetRoot<SrvDrone1DPIDMsg>(buf);
}

inline const SrvDrone1DPIDMsg *GetSizePrefixedSrvDrone1DPIDMsg(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SrvDrone1DPIDMsg>(buf);
}

inline const char *SrvDrone1DPIDMsgIdentifier() {
  return "S005";
}

inline bool SrvDrone1DPIDMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SrvDrone1DPIDMsgIdentifier());
}

inline bool SizePrefixedSrvDrone1DPIDMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SrvDrone1DPIDMsgIdentifier(), true);
}

inline bool VerifySrvDrone1DPIDMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SrvDrone1DPIDMsg>(SrvDrone1DPIDMsgIdentifier());
}

inline bool VerifySizePrefixedSrvDrone1DPIDMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SrvDrone1DPIDMsg>(SrvDrone1DPIDMsgIdentifier());
}

inline void FinishSrvDrone1DPIDMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SrvDrone1DPIDMsg> root) {
  fbb.Finish(root, SrvDrone1DPIDMsgIdentifier());
}

inline void FinishSizePrefixedSrvDrone1DPIDMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SrvDrone1DPIDMsg> root) {
  fbb.FinishSizePrefixed(root, SrvDrone1DPIDMsgIdentifier());
}

inline std::unique_ptr<SrvDrone1DPIDMsgT> UnPackSrvDrone1DPIDMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SrvDrone1DPIDMsgT>(GetSrvDrone1DPIDMsg(buf)->UnPack(res));
}

inline std::unique_ptr<SrvDrone1DPIDMsgT> UnPackSizePrefixedSrvDrone1DPIDMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SrvDrone1DPIDMsgT>(GetSizePrefixedSrvDrone1DPIDMsg(buf)->UnPack(res));
}

#endif  // FLATBUFFERS_GENERATED_S005SRVDRONE1DPIDMSG_H_
