// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COLLISION_H_
#define FLATBUFFERS_GENERATED_COLLISION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

struct Vec3Msg;
struct Vec3MsgBuilder;
struct Vec3MsgT;

struct Vec4Msg;
struct Vec4MsgBuilder;
struct Vec4MsgT;

struct Collision;
struct CollisionBuilder;
struct CollisionT;

struct Vec3MsgT : public ::flatbuffers::NativeTable {
  typedef Vec3Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
};

struct Vec3Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec3MsgT NativeTableType;
  typedef Vec3MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
  Vec3MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec3Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec3MsgBuilder {
  typedef Vec3Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec3Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec3Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec3Msg::VT_Z, z, 0.0f);
  }
  explicit Vec3MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec3Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec3Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f) {
  Vec3MsgBuilder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct Vec4MsgT : public ::flatbuffers::NativeTable {
  typedef Vec4Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
  float w = 0.0f;
};

struct Vec4Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec4MsgT NativeTableType;
  typedef Vec4MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8,
    VT_W = 10
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  float w() const {
    return GetField<float>(VT_W, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           VerifyField<float>(verifier, VT_W, 4) &&
           verifier.EndTable();
  }
  Vec4MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec4Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec4MsgBuilder {
  typedef Vec4Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec4Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec4Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec4Msg::VT_Z, z, 0.0f);
  }
  void add_w(float w) {
    fbb_.AddElement<float>(Vec4Msg::VT_W, w, 0.0f);
  }
  explicit Vec4MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec4Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec4Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f,
    float w = 0.0f) {
  Vec4MsgBuilder builder_(_fbb);
  builder_.add_w(w);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CollisionT : public ::flatbuffers::NativeTable {
  typedef Collision TableType;
  double timestamp = 0.0;
  uint8_t collision_type = 0;
  std::string object_name{};
  std::unique_ptr<Vec3MsgT> pos{};
  std::unique_ptr<Vec3MsgT> vel{};
  std::unique_ptr<Vec3MsgT> eul{};
  std::unique_ptr<Vec3MsgT> angvel{};
  CollisionT() = default;
  CollisionT(const CollisionT &o);
  CollisionT(CollisionT&&) FLATBUFFERS_NOEXCEPT = default;
  CollisionT &operator=(CollisionT o) FLATBUFFERS_NOEXCEPT;
};

struct Collision FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CollisionT NativeTableType;
  typedef CollisionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_COLLISION_TYPE = 6,
    VT_OBJECT_NAME = 8,
    VT_POS = 10,
    VT_VEL = 12,
    VT_EUL = 14,
    VT_ANGVEL = 16
  };
  double timestamp() const {
    return GetField<double>(VT_TIMESTAMP, 0.0);
  }
  uint8_t collision_type() const {
    return GetField<uint8_t>(VT_COLLISION_TYPE, 0);
  }
  const ::flatbuffers::String *object_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OBJECT_NAME);
  }
  const Vec3Msg *pos() const {
    return GetPointer<const Vec3Msg *>(VT_POS);
  }
  const Vec3Msg *vel() const {
    return GetPointer<const Vec3Msg *>(VT_VEL);
  }
  const Vec3Msg *eul() const {
    return GetPointer<const Vec3Msg *>(VT_EUL);
  }
  const Vec3Msg *angvel() const {
    return GetPointer<const Vec3Msg *>(VT_ANGVEL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<uint8_t>(verifier, VT_COLLISION_TYPE, 1) &&
           VerifyOffset(verifier, VT_OBJECT_NAME) &&
           verifier.VerifyString(object_name()) &&
           VerifyOffset(verifier, VT_POS) &&
           verifier.VerifyTable(pos()) &&
           VerifyOffset(verifier, VT_VEL) &&
           verifier.VerifyTable(vel()) &&
           VerifyOffset(verifier, VT_EUL) &&
           verifier.VerifyTable(eul()) &&
           VerifyOffset(verifier, VT_ANGVEL) &&
           verifier.VerifyTable(angvel()) &&
           verifier.EndTable();
  }
  CollisionT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CollisionT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Collision> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CollisionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CollisionBuilder {
  typedef Collision Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(double timestamp) {
    fbb_.AddElement<double>(Collision::VT_TIMESTAMP, timestamp, 0.0);
  }
  void add_collision_type(uint8_t collision_type) {
    fbb_.AddElement<uint8_t>(Collision::VT_COLLISION_TYPE, collision_type, 0);
  }
  void add_object_name(::flatbuffers::Offset<::flatbuffers::String> object_name) {
    fbb_.AddOffset(Collision::VT_OBJECT_NAME, object_name);
  }
  void add_pos(::flatbuffers::Offset<Vec3Msg> pos) {
    fbb_.AddOffset(Collision::VT_POS, pos);
  }
  void add_vel(::flatbuffers::Offset<Vec3Msg> vel) {
    fbb_.AddOffset(Collision::VT_VEL, vel);
  }
  void add_eul(::flatbuffers::Offset<Vec3Msg> eul) {
    fbb_.AddOffset(Collision::VT_EUL, eul);
  }
  void add_angvel(::flatbuffers::Offset<Vec3Msg> angvel) {
    fbb_.AddOffset(Collision::VT_ANGVEL, angvel);
  }
  explicit CollisionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Collision> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Collision>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Collision> CreateCollision(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double timestamp = 0.0,
    uint8_t collision_type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> object_name = 0,
    ::flatbuffers::Offset<Vec3Msg> pos = 0,
    ::flatbuffers::Offset<Vec3Msg> vel = 0,
    ::flatbuffers::Offset<Vec3Msg> eul = 0,
    ::flatbuffers::Offset<Vec3Msg> angvel = 0) {
  CollisionBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_angvel(angvel);
  builder_.add_eul(eul);
  builder_.add_vel(vel);
  builder_.add_pos(pos);
  builder_.add_object_name(object_name);
  builder_.add_collision_type(collision_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Collision> CreateCollisionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double timestamp = 0.0,
    uint8_t collision_type = 0,
    const char *object_name = nullptr,
    ::flatbuffers::Offset<Vec3Msg> pos = 0,
    ::flatbuffers::Offset<Vec3Msg> vel = 0,
    ::flatbuffers::Offset<Vec3Msg> eul = 0,
    ::flatbuffers::Offset<Vec3Msg> angvel = 0) {
  auto object_name__ = object_name ? _fbb.CreateString(object_name) : 0;
  return CreateCollision(
      _fbb,
      timestamp,
      collision_type,
      object_name__,
      pos,
      vel,
      eul,
      angvel);
}

::flatbuffers::Offset<Collision> CreateCollision(::flatbuffers::FlatBufferBuilder &_fbb, const CollisionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline Vec3MsgT *Vec3Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec3MsgT>(new Vec3MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec3Msg::UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
}

inline ::flatbuffers::Offset<Vec3Msg> Vec3Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec3Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec3MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  return CreateVec3Msg(
      _fbb,
      _x,
      _y,
      _z);
}

inline Vec4MsgT *Vec4Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec4MsgT>(new Vec4MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec4Msg::UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
  { auto _e = w(); _o->w = _e; }
}

inline ::flatbuffers::Offset<Vec4Msg> Vec4Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec4Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec4MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  auto _w = _o->w;
  return CreateVec4Msg(
      _fbb,
      _x,
      _y,
      _z,
      _w);
}

inline CollisionT::CollisionT(const CollisionT &o)
      : timestamp(o.timestamp),
        collision_type(o.collision_type),
        object_name(o.object_name),
        pos((o.pos) ? new Vec3MsgT(*o.pos) : nullptr),
        vel((o.vel) ? new Vec3MsgT(*o.vel) : nullptr),
        eul((o.eul) ? new Vec3MsgT(*o.eul) : nullptr),
        angvel((o.angvel) ? new Vec3MsgT(*o.angvel) : nullptr) {
}

inline CollisionT &CollisionT::operator=(CollisionT o) FLATBUFFERS_NOEXCEPT {
  std::swap(timestamp, o.timestamp);
  std::swap(collision_type, o.collision_type);
  std::swap(object_name, o.object_name);
  std::swap(pos, o.pos);
  std::swap(vel, o.vel);
  std::swap(eul, o.eul);
  std::swap(angvel, o.angvel);
  return *this;
}

inline CollisionT *Collision::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CollisionT>(new CollisionT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Collision::UnPackTo(CollisionT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = timestamp(); _o->timestamp = _e; }
  { auto _e = collision_type(); _o->collision_type = _e; }
  { auto _e = object_name(); if (_e) _o->object_name = _e->str(); }
  { auto _e = pos(); if (_e) { if(_o->pos) { _e->UnPackTo(_o->pos.get(), _resolver); } else { _o->pos = std::unique_ptr<Vec3MsgT>(_e->UnPack(_resolver)); } } else if (_o->pos) { _o->pos.reset(); } }
  { auto _e = vel(); if (_e) { if(_o->vel) { _e->UnPackTo(_o->vel.get(), _resolver); } else { _o->vel = std::unique_ptr<Vec3MsgT>(_e->UnPack(_resolver)); } } else if (_o->vel) { _o->vel.reset(); } }
  { auto _e = eul(); if (_e) { if(_o->eul) { _e->UnPackTo(_o->eul.get(), _resolver); } else { _o->eul = std::unique_ptr<Vec3MsgT>(_e->UnPack(_resolver)); } } else if (_o->eul) { _o->eul.reset(); } }
  { auto _e = angvel(); if (_e) { if(_o->angvel) { _e->UnPackTo(_o->angvel.get(), _resolver); } else { _o->angvel = std::unique_ptr<Vec3MsgT>(_e->UnPack(_resolver)); } } else if (_o->angvel) { _o->angvel.reset(); } }
}

inline ::flatbuffers::Offset<Collision> Collision::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CollisionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCollision(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Collision> CreateCollision(::flatbuffers::FlatBufferBuilder &_fbb, const CollisionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CollisionT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _timestamp = _o->timestamp;
  auto _collision_type = _o->collision_type;
  auto _object_name = _o->object_name.empty() ? 0 : _fbb.CreateString(_o->object_name);
  auto _pos = _o->pos ? CreateVec3Msg(_fbb, _o->pos.get(), _rehasher) : 0;
  auto _vel = _o->vel ? CreateVec3Msg(_fbb, _o->vel.get(), _rehasher) : 0;
  auto _eul = _o->eul ? CreateVec3Msg(_fbb, _o->eul.get(), _rehasher) : 0;
  auto _angvel = _o->angvel ? CreateVec3Msg(_fbb, _o->angvel.get(), _rehasher) : 0;
  return CreateCollision(
      _fbb,
      _timestamp,
      _collision_type,
      _object_name,
      _pos,
      _vel,
      _eul,
      _angvel);
}

#endif  // FLATBUFFERS_GENERATED_COLLISION_H_
