// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_S007SRVVROBOTPHYSICALPROPERTYMSG_H_
#define FLATBUFFERS_GENERATED_S007SRVVROBOTPHYSICALPROPERTYMSG_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

struct Vec3Msg;
struct Vec3MsgBuilder;
struct Vec3MsgT;

struct Vec4Msg;
struct Vec4MsgBuilder;
struct Vec4MsgT;

struct SrvVRobotPhysicalPropertyMsg;
struct SrvVRobotPhysicalPropertyMsgBuilder;
struct SrvVRobotPhysicalPropertyMsgT;

struct Vec3MsgT : public ::flatbuffers::NativeTable {
  typedef Vec3Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
};

struct Vec3Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec3MsgT NativeTableType;
  typedef Vec3MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
  Vec3MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec3Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec3MsgBuilder {
  typedef Vec3Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec3Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec3Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec3Msg::VT_Z, z, 0.0f);
  }
  explicit Vec3MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec3Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec3Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f) {
  Vec3MsgBuilder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct Vec4MsgT : public ::flatbuffers::NativeTable {
  typedef Vec4Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
  float w = 0.0f;
};

struct Vec4Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec4MsgT NativeTableType;
  typedef Vec4MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8,
    VT_W = 10
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  float w() const {
    return GetField<float>(VT_W, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           VerifyField<float>(verifier, VT_W, 4) &&
           verifier.EndTable();
  }
  Vec4MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec4Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec4MsgBuilder {
  typedef Vec4Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec4Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec4Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec4Msg::VT_Z, z, 0.0f);
  }
  void add_w(float w) {
    fbb_.AddElement<float>(Vec4Msg::VT_W, w, 0.0f);
  }
  explicit Vec4MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec4Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec4Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f,
    float w = 0.0f) {
  Vec4MsgBuilder builder_(_fbb);
  builder_.add_w(w);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SrvVRobotPhysicalPropertyMsgT : public ::flatbuffers::NativeTable {
  typedef SrvVRobotPhysicalPropertyMsg TableType;
  double timestamp = 0.0;
  std::string name{};
  uint32_t sys_id = 0;
  uint32_t req_src_id = 0;
  bool set_mass = false;
  float mass = 0.0f;
  bool set_moi3x1 = false;
  std::unique_ptr<Vec3MsgT> moi3x1{};
  SrvVRobotPhysicalPropertyMsgT() = default;
  SrvVRobotPhysicalPropertyMsgT(const SrvVRobotPhysicalPropertyMsgT &o);
  SrvVRobotPhysicalPropertyMsgT(SrvVRobotPhysicalPropertyMsgT&&) FLATBUFFERS_NOEXCEPT = default;
  SrvVRobotPhysicalPropertyMsgT &operator=(SrvVRobotPhysicalPropertyMsgT o) FLATBUFFERS_NOEXCEPT;
};

struct SrvVRobotPhysicalPropertyMsg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SrvVRobotPhysicalPropertyMsgT NativeTableType;
  typedef SrvVRobotPhysicalPropertyMsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_NAME = 6,
    VT_SYS_ID = 8,
    VT_REQ_SRC_ID = 10,
    VT_SET_MASS = 12,
    VT_MASS = 14,
    VT_SET_MOI3X1 = 16,
    VT_MOI3X1 = 18
  };
  double timestamp() const {
    return GetField<double>(VT_TIMESTAMP, 0.0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint32_t sys_id() const {
    return GetField<uint32_t>(VT_SYS_ID, 0);
  }
  uint32_t req_src_id() const {
    return GetField<uint32_t>(VT_REQ_SRC_ID, 0);
  }
  bool set_mass() const {
    return GetField<uint8_t>(VT_SET_MASS, 0) != 0;
  }
  float mass() const {
    return GetField<float>(VT_MASS, 0.0f);
  }
  bool set_moi3x1() const {
    return GetField<uint8_t>(VT_SET_MOI3X1, 0) != 0;
  }
  const Vec3Msg *moi3x1() const {
    return GetPointer<const Vec3Msg *>(VT_MOI3X1);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_TIMESTAMP, 8) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint32_t>(verifier, VT_SYS_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_REQ_SRC_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_SET_MASS, 1) &&
           VerifyField<float>(verifier, VT_MASS, 4) &&
           VerifyField<uint8_t>(verifier, VT_SET_MOI3X1, 1) &&
           VerifyOffset(verifier, VT_MOI3X1) &&
           verifier.VerifyTable(moi3x1()) &&
           verifier.EndTable();
  }
  SrvVRobotPhysicalPropertyMsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SrvVRobotPhysicalPropertyMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SrvVRobotPhysicalPropertyMsg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SrvVRobotPhysicalPropertyMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SrvVRobotPhysicalPropertyMsgBuilder {
  typedef SrvVRobotPhysicalPropertyMsg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(double timestamp) {
    fbb_.AddElement<double>(SrvVRobotPhysicalPropertyMsg::VT_TIMESTAMP, timestamp, 0.0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(SrvVRobotPhysicalPropertyMsg::VT_NAME, name);
  }
  void add_sys_id(uint32_t sys_id) {
    fbb_.AddElement<uint32_t>(SrvVRobotPhysicalPropertyMsg::VT_SYS_ID, sys_id, 0);
  }
  void add_req_src_id(uint32_t req_src_id) {
    fbb_.AddElement<uint32_t>(SrvVRobotPhysicalPropertyMsg::VT_REQ_SRC_ID, req_src_id, 0);
  }
  void add_set_mass(bool set_mass) {
    fbb_.AddElement<uint8_t>(SrvVRobotPhysicalPropertyMsg::VT_SET_MASS, static_cast<uint8_t>(set_mass), 0);
  }
  void add_mass(float mass) {
    fbb_.AddElement<float>(SrvVRobotPhysicalPropertyMsg::VT_MASS, mass, 0.0f);
  }
  void add_set_moi3x1(bool set_moi3x1) {
    fbb_.AddElement<uint8_t>(SrvVRobotPhysicalPropertyMsg::VT_SET_MOI3X1, static_cast<uint8_t>(set_moi3x1), 0);
  }
  void add_moi3x1(::flatbuffers::Offset<Vec3Msg> moi3x1) {
    fbb_.AddOffset(SrvVRobotPhysicalPropertyMsg::VT_MOI3X1, moi3x1);
  }
  explicit SrvVRobotPhysicalPropertyMsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SrvVRobotPhysicalPropertyMsg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SrvVRobotPhysicalPropertyMsg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SrvVRobotPhysicalPropertyMsg> CreateSrvVRobotPhysicalPropertyMsg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double timestamp = 0.0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint32_t sys_id = 0,
    uint32_t req_src_id = 0,
    bool set_mass = false,
    float mass = 0.0f,
    bool set_moi3x1 = false,
    ::flatbuffers::Offset<Vec3Msg> moi3x1 = 0) {
  SrvVRobotPhysicalPropertyMsgBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_moi3x1(moi3x1);
  builder_.add_mass(mass);
  builder_.add_req_src_id(req_src_id);
  builder_.add_sys_id(sys_id);
  builder_.add_name(name);
  builder_.add_set_moi3x1(set_moi3x1);
  builder_.add_set_mass(set_mass);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SrvVRobotPhysicalPropertyMsg> CreateSrvVRobotPhysicalPropertyMsgDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double timestamp = 0.0,
    const char *name = nullptr,
    uint32_t sys_id = 0,
    uint32_t req_src_id = 0,
    bool set_mass = false,
    float mass = 0.0f,
    bool set_moi3x1 = false,
    ::flatbuffers::Offset<Vec3Msg> moi3x1 = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return CreateSrvVRobotPhysicalPropertyMsg(
      _fbb,
      timestamp,
      name__,
      sys_id,
      req_src_id,
      set_mass,
      mass,
      set_moi3x1,
      moi3x1);
}

::flatbuffers::Offset<SrvVRobotPhysicalPropertyMsg> CreateSrvVRobotPhysicalPropertyMsg(::flatbuffers::FlatBufferBuilder &_fbb, const SrvVRobotPhysicalPropertyMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline Vec3MsgT *Vec3Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec3MsgT>(new Vec3MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec3Msg::UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
}

inline ::flatbuffers::Offset<Vec3Msg> Vec3Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec3Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec3MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  return CreateVec3Msg(
      _fbb,
      _x,
      _y,
      _z);
}

inline Vec4MsgT *Vec4Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec4MsgT>(new Vec4MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec4Msg::UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
  { auto _e = w(); _o->w = _e; }
}

inline ::flatbuffers::Offset<Vec4Msg> Vec4Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec4Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec4MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  auto _w = _o->w;
  return CreateVec4Msg(
      _fbb,
      _x,
      _y,
      _z,
      _w);
}

inline SrvVRobotPhysicalPropertyMsgT::SrvVRobotPhysicalPropertyMsgT(const SrvVRobotPhysicalPropertyMsgT &o)
      : timestamp(o.timestamp),
        name(o.name),
        sys_id(o.sys_id),
        req_src_id(o.req_src_id),
        set_mass(o.set_mass),
        mass(o.mass),
        set_moi3x1(o.set_moi3x1),
        moi3x1((o.moi3x1) ? new Vec3MsgT(*o.moi3x1) : nullptr) {
}

inline SrvVRobotPhysicalPropertyMsgT &SrvVRobotPhysicalPropertyMsgT::operator=(SrvVRobotPhysicalPropertyMsgT o) FLATBUFFERS_NOEXCEPT {
  std::swap(timestamp, o.timestamp);
  std::swap(name, o.name);
  std::swap(sys_id, o.sys_id);
  std::swap(req_src_id, o.req_src_id);
  std::swap(set_mass, o.set_mass);
  std::swap(mass, o.mass);
  std::swap(set_moi3x1, o.set_moi3x1);
  std::swap(moi3x1, o.moi3x1);
  return *this;
}

inline SrvVRobotPhysicalPropertyMsgT *SrvVRobotPhysicalPropertyMsg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SrvVRobotPhysicalPropertyMsgT>(new SrvVRobotPhysicalPropertyMsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SrvVRobotPhysicalPropertyMsg::UnPackTo(SrvVRobotPhysicalPropertyMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = timestamp(); _o->timestamp = _e; }
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = sys_id(); _o->sys_id = _e; }
  { auto _e = req_src_id(); _o->req_src_id = _e; }
  { auto _e = set_mass(); _o->set_mass = _e; }
  { auto _e = mass(); _o->mass = _e; }
  { auto _e = set_moi3x1(); _o->set_moi3x1 = _e; }
  { auto _e = moi3x1(); if (_e) { if(_o->moi3x1) { _e->UnPackTo(_o->moi3x1.get(), _resolver); } else { _o->moi3x1 = std::unique_ptr<Vec3MsgT>(_e->UnPack(_resolver)); } } else if (_o->moi3x1) { _o->moi3x1.reset(); } }
}

inline ::flatbuffers::Offset<SrvVRobotPhysicalPropertyMsg> SrvVRobotPhysicalPropertyMsg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SrvVRobotPhysicalPropertyMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSrvVRobotPhysicalPropertyMsg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SrvVRobotPhysicalPropertyMsg> CreateSrvVRobotPhysicalPropertyMsg(::flatbuffers::FlatBufferBuilder &_fbb, const SrvVRobotPhysicalPropertyMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SrvVRobotPhysicalPropertyMsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _timestamp = _o->timestamp;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _sys_id = _o->sys_id;
  auto _req_src_id = _o->req_src_id;
  auto _set_mass = _o->set_mass;
  auto _mass = _o->mass;
  auto _set_moi3x1 = _o->set_moi3x1;
  auto _moi3x1 = _o->moi3x1 ? CreateVec3Msg(_fbb, _o->moi3x1.get(), _rehasher) : 0;
  return CreateSrvVRobotPhysicalPropertyMsg(
      _fbb,
      _timestamp,
      _name,
      _sys_id,
      _req_src_id,
      _set_mass,
      _mass,
      _set_moi3x1,
      _moi3x1);
}

inline const SrvVRobotPhysicalPropertyMsg *GetSrvVRobotPhysicalPropertyMsg(const void *buf) {
  return ::flatbuffers::GetRoot<SrvVRobotPhysicalPropertyMsg>(buf);
}

inline const SrvVRobotPhysicalPropertyMsg *GetSizePrefixedSrvVRobotPhysicalPropertyMsg(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SrvVRobotPhysicalPropertyMsg>(buf);
}

inline const char *SrvVRobotPhysicalPropertyMsgIdentifier() {
  return "S007";
}

inline bool SrvVRobotPhysicalPropertyMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SrvVRobotPhysicalPropertyMsgIdentifier());
}

inline bool SizePrefixedSrvVRobotPhysicalPropertyMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SrvVRobotPhysicalPropertyMsgIdentifier(), true);
}

inline bool VerifySrvVRobotPhysicalPropertyMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SrvVRobotPhysicalPropertyMsg>(SrvVRobotPhysicalPropertyMsgIdentifier());
}

inline bool VerifySizePrefixedSrvVRobotPhysicalPropertyMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SrvVRobotPhysicalPropertyMsg>(SrvVRobotPhysicalPropertyMsgIdentifier());
}

inline void FinishSrvVRobotPhysicalPropertyMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SrvVRobotPhysicalPropertyMsg> root) {
  fbb.Finish(root, SrvVRobotPhysicalPropertyMsgIdentifier());
}

inline void FinishSizePrefixedSrvVRobotPhysicalPropertyMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SrvVRobotPhysicalPropertyMsg> root) {
  fbb.FinishSizePrefixed(root, SrvVRobotPhysicalPropertyMsgIdentifier());
}

inline std::unique_ptr<SrvVRobotPhysicalPropertyMsgT> UnPackSrvVRobotPhysicalPropertyMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SrvVRobotPhysicalPropertyMsgT>(GetSrvVRobotPhysicalPropertyMsg(buf)->UnPack(res));
}

inline std::unique_ptr<SrvVRobotPhysicalPropertyMsgT> UnPackSizePrefixedSrvVRobotPhysicalPropertyMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SrvVRobotPhysicalPropertyMsgT>(GetSizePrefixedSrvVRobotPhysicalPropertyMsg(buf)->UnPack(res));
}

#endif  // FLATBUFFERS_GENERATED_S007SRVVROBOTPHYSICALPROPERTYMSG_H_
