// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_S002SRVWSPARAMSMSG_H_
#define FLATBUFFERS_GENERATED_S002SRVWSPARAMSMSG_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

struct Vec3Msg;
struct Vec3MsgBuilder;
struct Vec3MsgT;

struct Vec4Msg;
struct Vec4MsgBuilder;
struct Vec4MsgT;

struct SrvWSParamsMsg;
struct SrvWSParamsMsgBuilder;
struct SrvWSParamsMsgT;

struct Vec3MsgT : public ::flatbuffers::NativeTable {
  typedef Vec3Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
};

struct Vec3Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec3MsgT NativeTableType;
  typedef Vec3MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
  Vec3MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec3Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec3MsgBuilder {
  typedef Vec3Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec3Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec3Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec3Msg::VT_Z, z, 0.0f);
  }
  explicit Vec3MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec3Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec3Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f) {
  Vec3MsgBuilder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct Vec4MsgT : public ::flatbuffers::NativeTable {
  typedef Vec4Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
  float w = 0.0f;
};

struct Vec4Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec4MsgT NativeTableType;
  typedef Vec4MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8,
    VT_W = 10
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  float w() const {
    return GetField<float>(VT_W, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           VerifyField<float>(verifier, VT_W, 4) &&
           verifier.EndTable();
  }
  Vec4MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec4Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec4MsgBuilder {
  typedef Vec4Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec4Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec4Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec4Msg::VT_Z, z, 0.0f);
  }
  void add_w(float w) {
    fbb_.AddElement<float>(Vec4Msg::VT_W, w, 0.0f);
  }
  explicit Vec4MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec4Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec4Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f,
    float w = 0.0f) {
  Vec4MsgBuilder builder_(_fbb);
  builder_.add_w(w);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SrvWSParamsMsgT : public ::flatbuffers::NativeTable {
  typedef SrvWSParamsMsg TableType;
  double timestamp = 0.0;
  std::string name{};
  uint32_t sys_id = 0;
  uint32_t req_src_id = 0;
  int32_t cmd_report_once = 0;
  int32_t cmd_connect = 0;
  int32_t cmd_disconnect = 0;
  bool is_connected = false;
  std::string current_url{};
  std::string prod_url{};
  std::string prod_port{};
  std::string dev_url{};
  std::string dev_port{};
  std::string set_prod_url{};
  std::string set_prod_port{};
  std::string set_dev_url{};
  std::string set_dev_port{};
};

struct SrvWSParamsMsg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SrvWSParamsMsgT NativeTableType;
  typedef SrvWSParamsMsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_NAME = 6,
    VT_SYS_ID = 8,
    VT_REQ_SRC_ID = 10,
    VT_CMD_REPORT_ONCE = 12,
    VT_CMD_CONNECT = 14,
    VT_CMD_DISCONNECT = 16,
    VT_IS_CONNECTED = 18,
    VT_CURRENT_URL = 20,
    VT_PROD_URL = 22,
    VT_PROD_PORT = 24,
    VT_DEV_URL = 26,
    VT_DEV_PORT = 28,
    VT_SET_PROD_URL = 30,
    VT_SET_PROD_PORT = 32,
    VT_SET_DEV_URL = 34,
    VT_SET_DEV_PORT = 36
  };
  double timestamp() const {
    return GetField<double>(VT_TIMESTAMP, 0.0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint32_t sys_id() const {
    return GetField<uint32_t>(VT_SYS_ID, 0);
  }
  uint32_t req_src_id() const {
    return GetField<uint32_t>(VT_REQ_SRC_ID, 0);
  }
  int32_t cmd_report_once() const {
    return GetField<int32_t>(VT_CMD_REPORT_ONCE, 0);
  }
  int32_t cmd_connect() const {
    return GetField<int32_t>(VT_CMD_CONNECT, 0);
  }
  int32_t cmd_disconnect() const {
    return GetField<int32_t>(VT_CMD_DISCONNECT, 0);
  }
  bool is_connected() const {
    return GetField<uint8_t>(VT_IS_CONNECTED, 0) != 0;
  }
  const ::flatbuffers::String *current_url() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CURRENT_URL);
  }
  const ::flatbuffers::String *prod_url() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROD_URL);
  }
  const ::flatbuffers::String *prod_port() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROD_PORT);
  }
  const ::flatbuffers::String *dev_url() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DEV_URL);
  }
  const ::flatbuffers::String *dev_port() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DEV_PORT);
  }
  const ::flatbuffers::String *set_prod_url() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SET_PROD_URL);
  }
  const ::flatbuffers::String *set_prod_port() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SET_PROD_PORT);
  }
  const ::flatbuffers::String *set_dev_url() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SET_DEV_URL);
  }
  const ::flatbuffers::String *set_dev_port() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SET_DEV_PORT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_TIMESTAMP, 8) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint32_t>(verifier, VT_SYS_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_REQ_SRC_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_CMD_REPORT_ONCE, 4) &&
           VerifyField<int32_t>(verifier, VT_CMD_CONNECT, 4) &&
           VerifyField<int32_t>(verifier, VT_CMD_DISCONNECT, 4) &&
           VerifyField<uint8_t>(verifier, VT_IS_CONNECTED, 1) &&
           VerifyOffset(verifier, VT_CURRENT_URL) &&
           verifier.VerifyString(current_url()) &&
           VerifyOffset(verifier, VT_PROD_URL) &&
           verifier.VerifyString(prod_url()) &&
           VerifyOffset(verifier, VT_PROD_PORT) &&
           verifier.VerifyString(prod_port()) &&
           VerifyOffset(verifier, VT_DEV_URL) &&
           verifier.VerifyString(dev_url()) &&
           VerifyOffset(verifier, VT_DEV_PORT) &&
           verifier.VerifyString(dev_port()) &&
           VerifyOffset(verifier, VT_SET_PROD_URL) &&
           verifier.VerifyString(set_prod_url()) &&
           VerifyOffset(verifier, VT_SET_PROD_PORT) &&
           verifier.VerifyString(set_prod_port()) &&
           VerifyOffset(verifier, VT_SET_DEV_URL) &&
           verifier.VerifyString(set_dev_url()) &&
           VerifyOffset(verifier, VT_SET_DEV_PORT) &&
           verifier.VerifyString(set_dev_port()) &&
           verifier.EndTable();
  }
  SrvWSParamsMsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SrvWSParamsMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SrvWSParamsMsg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SrvWSParamsMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SrvWSParamsMsgBuilder {
  typedef SrvWSParamsMsg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(double timestamp) {
    fbb_.AddElement<double>(SrvWSParamsMsg::VT_TIMESTAMP, timestamp, 0.0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(SrvWSParamsMsg::VT_NAME, name);
  }
  void add_sys_id(uint32_t sys_id) {
    fbb_.AddElement<uint32_t>(SrvWSParamsMsg::VT_SYS_ID, sys_id, 0);
  }
  void add_req_src_id(uint32_t req_src_id) {
    fbb_.AddElement<uint32_t>(SrvWSParamsMsg::VT_REQ_SRC_ID, req_src_id, 0);
  }
  void add_cmd_report_once(int32_t cmd_report_once) {
    fbb_.AddElement<int32_t>(SrvWSParamsMsg::VT_CMD_REPORT_ONCE, cmd_report_once, 0);
  }
  void add_cmd_connect(int32_t cmd_connect) {
    fbb_.AddElement<int32_t>(SrvWSParamsMsg::VT_CMD_CONNECT, cmd_connect, 0);
  }
  void add_cmd_disconnect(int32_t cmd_disconnect) {
    fbb_.AddElement<int32_t>(SrvWSParamsMsg::VT_CMD_DISCONNECT, cmd_disconnect, 0);
  }
  void add_is_connected(bool is_connected) {
    fbb_.AddElement<uint8_t>(SrvWSParamsMsg::VT_IS_CONNECTED, static_cast<uint8_t>(is_connected), 0);
  }
  void add_current_url(::flatbuffers::Offset<::flatbuffers::String> current_url) {
    fbb_.AddOffset(SrvWSParamsMsg::VT_CURRENT_URL, current_url);
  }
  void add_prod_url(::flatbuffers::Offset<::flatbuffers::String> prod_url) {
    fbb_.AddOffset(SrvWSParamsMsg::VT_PROD_URL, prod_url);
  }
  void add_prod_port(::flatbuffers::Offset<::flatbuffers::String> prod_port) {
    fbb_.AddOffset(SrvWSParamsMsg::VT_PROD_PORT, prod_port);
  }
  void add_dev_url(::flatbuffers::Offset<::flatbuffers::String> dev_url) {
    fbb_.AddOffset(SrvWSParamsMsg::VT_DEV_URL, dev_url);
  }
  void add_dev_port(::flatbuffers::Offset<::flatbuffers::String> dev_port) {
    fbb_.AddOffset(SrvWSParamsMsg::VT_DEV_PORT, dev_port);
  }
  void add_set_prod_url(::flatbuffers::Offset<::flatbuffers::String> set_prod_url) {
    fbb_.AddOffset(SrvWSParamsMsg::VT_SET_PROD_URL, set_prod_url);
  }
  void add_set_prod_port(::flatbuffers::Offset<::flatbuffers::String> set_prod_port) {
    fbb_.AddOffset(SrvWSParamsMsg::VT_SET_PROD_PORT, set_prod_port);
  }
  void add_set_dev_url(::flatbuffers::Offset<::flatbuffers::String> set_dev_url) {
    fbb_.AddOffset(SrvWSParamsMsg::VT_SET_DEV_URL, set_dev_url);
  }
  void add_set_dev_port(::flatbuffers::Offset<::flatbuffers::String> set_dev_port) {
    fbb_.AddOffset(SrvWSParamsMsg::VT_SET_DEV_PORT, set_dev_port);
  }
  explicit SrvWSParamsMsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SrvWSParamsMsg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SrvWSParamsMsg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SrvWSParamsMsg> CreateSrvWSParamsMsg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double timestamp = 0.0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint32_t sys_id = 0,
    uint32_t req_src_id = 0,
    int32_t cmd_report_once = 0,
    int32_t cmd_connect = 0,
    int32_t cmd_disconnect = 0,
    bool is_connected = false,
    ::flatbuffers::Offset<::flatbuffers::String> current_url = 0,
    ::flatbuffers::Offset<::flatbuffers::String> prod_url = 0,
    ::flatbuffers::Offset<::flatbuffers::String> prod_port = 0,
    ::flatbuffers::Offset<::flatbuffers::String> dev_url = 0,
    ::flatbuffers::Offset<::flatbuffers::String> dev_port = 0,
    ::flatbuffers::Offset<::flatbuffers::String> set_prod_url = 0,
    ::flatbuffers::Offset<::flatbuffers::String> set_prod_port = 0,
    ::flatbuffers::Offset<::flatbuffers::String> set_dev_url = 0,
    ::flatbuffers::Offset<::flatbuffers::String> set_dev_port = 0) {
  SrvWSParamsMsgBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_set_dev_port(set_dev_port);
  builder_.add_set_dev_url(set_dev_url);
  builder_.add_set_prod_port(set_prod_port);
  builder_.add_set_prod_url(set_prod_url);
  builder_.add_dev_port(dev_port);
  builder_.add_dev_url(dev_url);
  builder_.add_prod_port(prod_port);
  builder_.add_prod_url(prod_url);
  builder_.add_current_url(current_url);
  builder_.add_cmd_disconnect(cmd_disconnect);
  builder_.add_cmd_connect(cmd_connect);
  builder_.add_cmd_report_once(cmd_report_once);
  builder_.add_req_src_id(req_src_id);
  builder_.add_sys_id(sys_id);
  builder_.add_name(name);
  builder_.add_is_connected(is_connected);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SrvWSParamsMsg> CreateSrvWSParamsMsgDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double timestamp = 0.0,
    const char *name = nullptr,
    uint32_t sys_id = 0,
    uint32_t req_src_id = 0,
    int32_t cmd_report_once = 0,
    int32_t cmd_connect = 0,
    int32_t cmd_disconnect = 0,
    bool is_connected = false,
    const char *current_url = nullptr,
    const char *prod_url = nullptr,
    const char *prod_port = nullptr,
    const char *dev_url = nullptr,
    const char *dev_port = nullptr,
    const char *set_prod_url = nullptr,
    const char *set_prod_port = nullptr,
    const char *set_dev_url = nullptr,
    const char *set_dev_port = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto current_url__ = current_url ? _fbb.CreateString(current_url) : 0;
  auto prod_url__ = prod_url ? _fbb.CreateString(prod_url) : 0;
  auto prod_port__ = prod_port ? _fbb.CreateString(prod_port) : 0;
  auto dev_url__ = dev_url ? _fbb.CreateString(dev_url) : 0;
  auto dev_port__ = dev_port ? _fbb.CreateString(dev_port) : 0;
  auto set_prod_url__ = set_prod_url ? _fbb.CreateString(set_prod_url) : 0;
  auto set_prod_port__ = set_prod_port ? _fbb.CreateString(set_prod_port) : 0;
  auto set_dev_url__ = set_dev_url ? _fbb.CreateString(set_dev_url) : 0;
  auto set_dev_port__ = set_dev_port ? _fbb.CreateString(set_dev_port) : 0;
  return CreateSrvWSParamsMsg(
      _fbb,
      timestamp,
      name__,
      sys_id,
      req_src_id,
      cmd_report_once,
      cmd_connect,
      cmd_disconnect,
      is_connected,
      current_url__,
      prod_url__,
      prod_port__,
      dev_url__,
      dev_port__,
      set_prod_url__,
      set_prod_port__,
      set_dev_url__,
      set_dev_port__);
}

::flatbuffers::Offset<SrvWSParamsMsg> CreateSrvWSParamsMsg(::flatbuffers::FlatBufferBuilder &_fbb, const SrvWSParamsMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline Vec3MsgT *Vec3Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec3MsgT>(new Vec3MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec3Msg::UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
}

inline ::flatbuffers::Offset<Vec3Msg> Vec3Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec3Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec3MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  return CreateVec3Msg(
      _fbb,
      _x,
      _y,
      _z);
}

inline Vec4MsgT *Vec4Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec4MsgT>(new Vec4MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec4Msg::UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
  { auto _e = w(); _o->w = _e; }
}

inline ::flatbuffers::Offset<Vec4Msg> Vec4Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec4Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec4MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  auto _w = _o->w;
  return CreateVec4Msg(
      _fbb,
      _x,
      _y,
      _z,
      _w);
}

inline SrvWSParamsMsgT *SrvWSParamsMsg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SrvWSParamsMsgT>(new SrvWSParamsMsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SrvWSParamsMsg::UnPackTo(SrvWSParamsMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = timestamp(); _o->timestamp = _e; }
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = sys_id(); _o->sys_id = _e; }
  { auto _e = req_src_id(); _o->req_src_id = _e; }
  { auto _e = cmd_report_once(); _o->cmd_report_once = _e; }
  { auto _e = cmd_connect(); _o->cmd_connect = _e; }
  { auto _e = cmd_disconnect(); _o->cmd_disconnect = _e; }
  { auto _e = is_connected(); _o->is_connected = _e; }
  { auto _e = current_url(); if (_e) _o->current_url = _e->str(); }
  { auto _e = prod_url(); if (_e) _o->prod_url = _e->str(); }
  { auto _e = prod_port(); if (_e) _o->prod_port = _e->str(); }
  { auto _e = dev_url(); if (_e) _o->dev_url = _e->str(); }
  { auto _e = dev_port(); if (_e) _o->dev_port = _e->str(); }
  { auto _e = set_prod_url(); if (_e) _o->set_prod_url = _e->str(); }
  { auto _e = set_prod_port(); if (_e) _o->set_prod_port = _e->str(); }
  { auto _e = set_dev_url(); if (_e) _o->set_dev_url = _e->str(); }
  { auto _e = set_dev_port(); if (_e) _o->set_dev_port = _e->str(); }
}

inline ::flatbuffers::Offset<SrvWSParamsMsg> SrvWSParamsMsg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SrvWSParamsMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSrvWSParamsMsg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SrvWSParamsMsg> CreateSrvWSParamsMsg(::flatbuffers::FlatBufferBuilder &_fbb, const SrvWSParamsMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SrvWSParamsMsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _timestamp = _o->timestamp;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _sys_id = _o->sys_id;
  auto _req_src_id = _o->req_src_id;
  auto _cmd_report_once = _o->cmd_report_once;
  auto _cmd_connect = _o->cmd_connect;
  auto _cmd_disconnect = _o->cmd_disconnect;
  auto _is_connected = _o->is_connected;
  auto _current_url = _o->current_url.empty() ? 0 : _fbb.CreateString(_o->current_url);
  auto _prod_url = _o->prod_url.empty() ? 0 : _fbb.CreateString(_o->prod_url);
  auto _prod_port = _o->prod_port.empty() ? 0 : _fbb.CreateString(_o->prod_port);
  auto _dev_url = _o->dev_url.empty() ? 0 : _fbb.CreateString(_o->dev_url);
  auto _dev_port = _o->dev_port.empty() ? 0 : _fbb.CreateString(_o->dev_port);
  auto _set_prod_url = _o->set_prod_url.empty() ? 0 : _fbb.CreateString(_o->set_prod_url);
  auto _set_prod_port = _o->set_prod_port.empty() ? 0 : _fbb.CreateString(_o->set_prod_port);
  auto _set_dev_url = _o->set_dev_url.empty() ? 0 : _fbb.CreateString(_o->set_dev_url);
  auto _set_dev_port = _o->set_dev_port.empty() ? 0 : _fbb.CreateString(_o->set_dev_port);
  return CreateSrvWSParamsMsg(
      _fbb,
      _timestamp,
      _name,
      _sys_id,
      _req_src_id,
      _cmd_report_once,
      _cmd_connect,
      _cmd_disconnect,
      _is_connected,
      _current_url,
      _prod_url,
      _prod_port,
      _dev_url,
      _dev_port,
      _set_prod_url,
      _set_prod_port,
      _set_dev_url,
      _set_dev_port);
}

inline const SrvWSParamsMsg *GetSrvWSParamsMsg(const void *buf) {
  return ::flatbuffers::GetRoot<SrvWSParamsMsg>(buf);
}

inline const SrvWSParamsMsg *GetSizePrefixedSrvWSParamsMsg(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SrvWSParamsMsg>(buf);
}

inline const char *SrvWSParamsMsgIdentifier() {
  return "S002";
}

inline bool SrvWSParamsMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SrvWSParamsMsgIdentifier());
}

inline bool SizePrefixedSrvWSParamsMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SrvWSParamsMsgIdentifier(), true);
}

inline bool VerifySrvWSParamsMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SrvWSParamsMsg>(SrvWSParamsMsgIdentifier());
}

inline bool VerifySizePrefixedSrvWSParamsMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SrvWSParamsMsg>(SrvWSParamsMsgIdentifier());
}

inline void FinishSrvWSParamsMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SrvWSParamsMsg> root) {
  fbb.Finish(root, SrvWSParamsMsgIdentifier());
}

inline void FinishSizePrefixedSrvWSParamsMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SrvWSParamsMsg> root) {
  fbb.FinishSizePrefixed(root, SrvWSParamsMsgIdentifier());
}

inline std::unique_ptr<SrvWSParamsMsgT> UnPackSrvWSParamsMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SrvWSParamsMsgT>(GetSrvWSParamsMsg(buf)->UnPack(res));
}

inline std::unique_ptr<SrvWSParamsMsgT> UnPackSizePrefixedSrvWSParamsMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SrvWSParamsMsgT>(GetSizePrefixedSrvWSParamsMsg(buf)->UnPack(res));
}

#endif  // FLATBUFFERS_GENERATED_S002SRVWSPARAMSMSG_H_
