// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_EMPTEMPTY_H_
#define FLATBUFFERS_GENERATED_EMPTEMPTY_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

struct EmptyMsg;
struct EmptyMsgBuilder;
struct EmptyMsgT;

struct EmptyMsgT : public ::flatbuffers::NativeTable {
  typedef EmptyMsg TableType;
  int8_t idx = 0;
};

struct EmptyMsg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EmptyMsgT NativeTableType;
  typedef EmptyMsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IDX = 4
  };
  int8_t idx() const {
    return GetField<int8_t>(VT_IDX, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_IDX, 1) &&
           verifier.EndTable();
  }
  EmptyMsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(EmptyMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<EmptyMsg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EmptyMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct EmptyMsgBuilder {
  typedef EmptyMsg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_idx(int8_t idx) {
    fbb_.AddElement<int8_t>(EmptyMsg::VT_IDX, idx, 0);
  }
  explicit EmptyMsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EmptyMsg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EmptyMsg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EmptyMsg> CreateEmptyMsg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int8_t idx = 0) {
  EmptyMsgBuilder builder_(_fbb);
  builder_.add_idx(idx);
  return builder_.Finish();
}

::flatbuffers::Offset<EmptyMsg> CreateEmptyMsg(::flatbuffers::FlatBufferBuilder &_fbb, const EmptyMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline EmptyMsgT *EmptyMsg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<EmptyMsgT>(new EmptyMsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void EmptyMsg::UnPackTo(EmptyMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = idx(); _o->idx = _e; }
}

inline ::flatbuffers::Offset<EmptyMsg> EmptyMsg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EmptyMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateEmptyMsg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<EmptyMsg> CreateEmptyMsg(::flatbuffers::FlatBufferBuilder &_fbb, const EmptyMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const EmptyMsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _idx = _o->idx;
  return CreateEmptyMsg(
      _fbb,
      _idx);
}

inline const EmptyMsg *GetEmptyMsg(const void *buf) {
  return ::flatbuffers::GetRoot<EmptyMsg>(buf);
}

inline const EmptyMsg *GetSizePrefixedEmptyMsg(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<EmptyMsg>(buf);
}

inline const char *EmptyMsgIdentifier() {
  return "EMPT";
}

inline bool EmptyMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, EmptyMsgIdentifier());
}

inline bool SizePrefixedEmptyMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, EmptyMsgIdentifier(), true);
}

inline bool VerifyEmptyMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<EmptyMsg>(EmptyMsgIdentifier());
}

inline bool VerifySizePrefixedEmptyMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<EmptyMsg>(EmptyMsgIdentifier());
}

inline void FinishEmptyMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<EmptyMsg> root) {
  fbb.Finish(root, EmptyMsgIdentifier());
}

inline void FinishSizePrefixedEmptyMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<EmptyMsg> root) {
  fbb.FinishSizePrefixed(root, EmptyMsgIdentifier());
}

inline std::unique_ptr<EmptyMsgT> UnPackEmptyMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<EmptyMsgT>(GetEmptyMsg(buf)->UnPack(res));
}

inline std::unique_ptr<EmptyMsgT> UnPackSizePrefixedEmptyMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<EmptyMsgT>(GetSizePrefixedEmptyMsg(buf)->UnPack(res));
}

#endif  // FLATBUFFERS_GENERATED_EMPTEMPTY_H_
