// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_C000COMMANDS_H_
#define FLATBUFFERS_GENERATED_C000COMMANDS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

struct Vec3Msg;
struct Vec3MsgBuilder;
struct Vec3MsgT;

struct Vec4Msg;
struct Vec4MsgBuilder;
struct Vec4MsgT;

struct CommandMsg;
struct CommandMsgBuilder;
struct CommandMsgT;

struct Vec3MsgT : public ::flatbuffers::NativeTable {
  typedef Vec3Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
};

struct Vec3Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec3MsgT NativeTableType;
  typedef Vec3MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
  Vec3MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec3Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec3MsgBuilder {
  typedef Vec3Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec3Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec3Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec3Msg::VT_Z, z, 0.0f);
  }
  explicit Vec3MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec3Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec3Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f) {
  Vec3MsgBuilder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct Vec4MsgT : public ::flatbuffers::NativeTable {
  typedef Vec4Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
  float w = 0.0f;
};

struct Vec4Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec4MsgT NativeTableType;
  typedef Vec4MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8,
    VT_W = 10
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  float w() const {
    return GetField<float>(VT_W, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           VerifyField<float>(verifier, VT_W, 4) &&
           verifier.EndTable();
  }
  Vec4MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec4Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec4MsgBuilder {
  typedef Vec4Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec4Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec4Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec4Msg::VT_Z, z, 0.0f);
  }
  void add_w(float w) {
    fbb_.AddElement<float>(Vec4Msg::VT_W, w, 0.0f);
  }
  explicit Vec4MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec4Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec4Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f,
    float w = 0.0f) {
  Vec4MsgBuilder builder_(_fbb);
  builder_.add_w(w);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CommandMsgT : public ::flatbuffers::NativeTable {
  typedef CommandMsg TableType;
  std::string name{};
  double timestamp = 0.0;
  uint32_t cmd_id = 0;
  uint32_t sys_id = 0;
  int32_t int_val = 0;
  float float_val = 0.0f;
  std::vector<int32_t> int_arr{};
  std::vector<float> float_arr{};
  std::unique_ptr<Vec3MsgT> vec3{};
  std::unique_ptr<Vec4MsgT> vec4{};
  std::vector<std::unique_ptr<Vec3MsgT>> vec3_arr{};
  std::vector<std::unique_ptr<Vec4MsgT>> vec4_arr{};
  CommandMsgT() = default;
  CommandMsgT(const CommandMsgT &o);
  CommandMsgT(CommandMsgT&&) FLATBUFFERS_NOEXCEPT = default;
  CommandMsgT &operator=(CommandMsgT o) FLATBUFFERS_NOEXCEPT;
};

struct CommandMsg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CommandMsgT NativeTableType;
  typedef CommandMsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_TIMESTAMP = 6,
    VT_CMD_ID = 8,
    VT_SYS_ID = 10,
    VT_INT_VAL = 12,
    VT_FLOAT_VAL = 14,
    VT_INT_ARR = 16,
    VT_FLOAT_ARR = 18,
    VT_VEC3 = 20,
    VT_VEC4 = 22,
    VT_VEC3_ARR = 24,
    VT_VEC4_ARR = 26
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  double timestamp() const {
    return GetField<double>(VT_TIMESTAMP, 0.0);
  }
  uint32_t cmd_id() const {
    return GetField<uint32_t>(VT_CMD_ID, 0);
  }
  uint32_t sys_id() const {
    return GetField<uint32_t>(VT_SYS_ID, 0);
  }
  int32_t int_val() const {
    return GetField<int32_t>(VT_INT_VAL, 0);
  }
  float float_val() const {
    return GetField<float>(VT_FLOAT_VAL, 0.0f);
  }
  const ::flatbuffers::Vector<int32_t> *int_arr() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_INT_ARR);
  }
  const ::flatbuffers::Vector<float> *float_arr() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_FLOAT_ARR);
  }
  const Vec3Msg *vec3() const {
    return GetPointer<const Vec3Msg *>(VT_VEC3);
  }
  const Vec4Msg *vec4() const {
    return GetPointer<const Vec4Msg *>(VT_VEC4);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Vec3Msg>> *vec3_arr() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Vec3Msg>> *>(VT_VEC3_ARR);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Vec4Msg>> *vec4_arr() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Vec4Msg>> *>(VT_VEC4_ARR);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<double>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<uint32_t>(verifier, VT_CMD_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_SYS_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_INT_VAL, 4) &&
           VerifyField<float>(verifier, VT_FLOAT_VAL, 4) &&
           VerifyOffset(verifier, VT_INT_ARR) &&
           verifier.VerifyVector(int_arr()) &&
           VerifyOffset(verifier, VT_FLOAT_ARR) &&
           verifier.VerifyVector(float_arr()) &&
           VerifyOffset(verifier, VT_VEC3) &&
           verifier.VerifyTable(vec3()) &&
           VerifyOffset(verifier, VT_VEC4) &&
           verifier.VerifyTable(vec4()) &&
           VerifyOffset(verifier, VT_VEC3_ARR) &&
           verifier.VerifyVector(vec3_arr()) &&
           verifier.VerifyVectorOfTables(vec3_arr()) &&
           VerifyOffset(verifier, VT_VEC4_ARR) &&
           verifier.VerifyVector(vec4_arr()) &&
           verifier.VerifyVectorOfTables(vec4_arr()) &&
           verifier.EndTable();
  }
  CommandMsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CommandMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CommandMsg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CommandMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CommandMsgBuilder {
  typedef CommandMsg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(CommandMsg::VT_NAME, name);
  }
  void add_timestamp(double timestamp) {
    fbb_.AddElement<double>(CommandMsg::VT_TIMESTAMP, timestamp, 0.0);
  }
  void add_cmd_id(uint32_t cmd_id) {
    fbb_.AddElement<uint32_t>(CommandMsg::VT_CMD_ID, cmd_id, 0);
  }
  void add_sys_id(uint32_t sys_id) {
    fbb_.AddElement<uint32_t>(CommandMsg::VT_SYS_ID, sys_id, 0);
  }
  void add_int_val(int32_t int_val) {
    fbb_.AddElement<int32_t>(CommandMsg::VT_INT_VAL, int_val, 0);
  }
  void add_float_val(float float_val) {
    fbb_.AddElement<float>(CommandMsg::VT_FLOAT_VAL, float_val, 0.0f);
  }
  void add_int_arr(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> int_arr) {
    fbb_.AddOffset(CommandMsg::VT_INT_ARR, int_arr);
  }
  void add_float_arr(::flatbuffers::Offset<::flatbuffers::Vector<float>> float_arr) {
    fbb_.AddOffset(CommandMsg::VT_FLOAT_ARR, float_arr);
  }
  void add_vec3(::flatbuffers::Offset<Vec3Msg> vec3) {
    fbb_.AddOffset(CommandMsg::VT_VEC3, vec3);
  }
  void add_vec4(::flatbuffers::Offset<Vec4Msg> vec4) {
    fbb_.AddOffset(CommandMsg::VT_VEC4, vec4);
  }
  void add_vec3_arr(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Vec3Msg>>> vec3_arr) {
    fbb_.AddOffset(CommandMsg::VT_VEC3_ARR, vec3_arr);
  }
  void add_vec4_arr(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Vec4Msg>>> vec4_arr) {
    fbb_.AddOffset(CommandMsg::VT_VEC4_ARR, vec4_arr);
  }
  explicit CommandMsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CommandMsg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CommandMsg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CommandMsg> CreateCommandMsg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    double timestamp = 0.0,
    uint32_t cmd_id = 0,
    uint32_t sys_id = 0,
    int32_t int_val = 0,
    float float_val = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> int_arr = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> float_arr = 0,
    ::flatbuffers::Offset<Vec3Msg> vec3 = 0,
    ::flatbuffers::Offset<Vec4Msg> vec4 = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Vec3Msg>>> vec3_arr = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Vec4Msg>>> vec4_arr = 0) {
  CommandMsgBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_vec4_arr(vec4_arr);
  builder_.add_vec3_arr(vec3_arr);
  builder_.add_vec4(vec4);
  builder_.add_vec3(vec3);
  builder_.add_float_arr(float_arr);
  builder_.add_int_arr(int_arr);
  builder_.add_float_val(float_val);
  builder_.add_int_val(int_val);
  builder_.add_sys_id(sys_id);
  builder_.add_cmd_id(cmd_id);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CommandMsg> CreateCommandMsgDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    double timestamp = 0.0,
    uint32_t cmd_id = 0,
    uint32_t sys_id = 0,
    int32_t int_val = 0,
    float float_val = 0.0f,
    const std::vector<int32_t> *int_arr = nullptr,
    const std::vector<float> *float_arr = nullptr,
    ::flatbuffers::Offset<Vec3Msg> vec3 = 0,
    ::flatbuffers::Offset<Vec4Msg> vec4 = 0,
    const std::vector<::flatbuffers::Offset<Vec3Msg>> *vec3_arr = nullptr,
    const std::vector<::flatbuffers::Offset<Vec4Msg>> *vec4_arr = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto int_arr__ = int_arr ? _fbb.CreateVector<int32_t>(*int_arr) : 0;
  auto float_arr__ = float_arr ? _fbb.CreateVector<float>(*float_arr) : 0;
  auto vec3_arr__ = vec3_arr ? _fbb.CreateVector<::flatbuffers::Offset<Vec3Msg>>(*vec3_arr) : 0;
  auto vec4_arr__ = vec4_arr ? _fbb.CreateVector<::flatbuffers::Offset<Vec4Msg>>(*vec4_arr) : 0;
  return CreateCommandMsg(
      _fbb,
      name__,
      timestamp,
      cmd_id,
      sys_id,
      int_val,
      float_val,
      int_arr__,
      float_arr__,
      vec3,
      vec4,
      vec3_arr__,
      vec4_arr__);
}

::flatbuffers::Offset<CommandMsg> CreateCommandMsg(::flatbuffers::FlatBufferBuilder &_fbb, const CommandMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline Vec3MsgT *Vec3Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec3MsgT>(new Vec3MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec3Msg::UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
}

inline ::flatbuffers::Offset<Vec3Msg> Vec3Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec3Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec3MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  return CreateVec3Msg(
      _fbb,
      _x,
      _y,
      _z);
}

inline Vec4MsgT *Vec4Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec4MsgT>(new Vec4MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec4Msg::UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
  { auto _e = w(); _o->w = _e; }
}

inline ::flatbuffers::Offset<Vec4Msg> Vec4Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec4Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec4MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  auto _w = _o->w;
  return CreateVec4Msg(
      _fbb,
      _x,
      _y,
      _z,
      _w);
}

inline CommandMsgT::CommandMsgT(const CommandMsgT &o)
      : name(o.name),
        timestamp(o.timestamp),
        cmd_id(o.cmd_id),
        sys_id(o.sys_id),
        int_val(o.int_val),
        float_val(o.float_val),
        int_arr(o.int_arr),
        float_arr(o.float_arr),
        vec3((o.vec3) ? new Vec3MsgT(*o.vec3) : nullptr),
        vec4((o.vec4) ? new Vec4MsgT(*o.vec4) : nullptr) {
  vec3_arr.reserve(o.vec3_arr.size());
  for (const auto &vec3_arr_ : o.vec3_arr) { vec3_arr.emplace_back((vec3_arr_) ? new Vec3MsgT(*vec3_arr_) : nullptr); }
  vec4_arr.reserve(o.vec4_arr.size());
  for (const auto &vec4_arr_ : o.vec4_arr) { vec4_arr.emplace_back((vec4_arr_) ? new Vec4MsgT(*vec4_arr_) : nullptr); }
}

inline CommandMsgT &CommandMsgT::operator=(CommandMsgT o) FLATBUFFERS_NOEXCEPT {
  std::swap(name, o.name);
  std::swap(timestamp, o.timestamp);
  std::swap(cmd_id, o.cmd_id);
  std::swap(sys_id, o.sys_id);
  std::swap(int_val, o.int_val);
  std::swap(float_val, o.float_val);
  std::swap(int_arr, o.int_arr);
  std::swap(float_arr, o.float_arr);
  std::swap(vec3, o.vec3);
  std::swap(vec4, o.vec4);
  std::swap(vec3_arr, o.vec3_arr);
  std::swap(vec4_arr, o.vec4_arr);
  return *this;
}

inline CommandMsgT *CommandMsg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CommandMsgT>(new CommandMsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CommandMsg::UnPackTo(CommandMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = timestamp(); _o->timestamp = _e; }
  { auto _e = cmd_id(); _o->cmd_id = _e; }
  { auto _e = sys_id(); _o->sys_id = _e; }
  { auto _e = int_val(); _o->int_val = _e; }
  { auto _e = float_val(); _o->float_val = _e; }
  { auto _e = int_arr(); if (_e) { _o->int_arr.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->int_arr[_i] = _e->Get(_i); } } else { _o->int_arr.resize(0); } }
  { auto _e = float_arr(); if (_e) { _o->float_arr.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->float_arr[_i] = _e->Get(_i); } } else { _o->float_arr.resize(0); } }
  { auto _e = vec3(); if (_e) { if(_o->vec3) { _e->UnPackTo(_o->vec3.get(), _resolver); } else { _o->vec3 = std::unique_ptr<Vec3MsgT>(_e->UnPack(_resolver)); } } else if (_o->vec3) { _o->vec3.reset(); } }
  { auto _e = vec4(); if (_e) { if(_o->vec4) { _e->UnPackTo(_o->vec4.get(), _resolver); } else { _o->vec4 = std::unique_ptr<Vec4MsgT>(_e->UnPack(_resolver)); } } else if (_o->vec4) { _o->vec4.reset(); } }
  { auto _e = vec3_arr(); if (_e) { _o->vec3_arr.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->vec3_arr[_i]) { _e->Get(_i)->UnPackTo(_o->vec3_arr[_i].get(), _resolver); } else { _o->vec3_arr[_i] = std::unique_ptr<Vec3MsgT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->vec3_arr.resize(0); } }
  { auto _e = vec4_arr(); if (_e) { _o->vec4_arr.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->vec4_arr[_i]) { _e->Get(_i)->UnPackTo(_o->vec4_arr[_i].get(), _resolver); } else { _o->vec4_arr[_i] = std::unique_ptr<Vec4MsgT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->vec4_arr.resize(0); } }
}

inline ::flatbuffers::Offset<CommandMsg> CommandMsg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CommandMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCommandMsg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CommandMsg> CreateCommandMsg(::flatbuffers::FlatBufferBuilder &_fbb, const CommandMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CommandMsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _timestamp = _o->timestamp;
  auto _cmd_id = _o->cmd_id;
  auto _sys_id = _o->sys_id;
  auto _int_val = _o->int_val;
  auto _float_val = _o->float_val;
  auto _int_arr = _o->int_arr.size() ? _fbb.CreateVector(_o->int_arr) : 0;
  auto _float_arr = _o->float_arr.size() ? _fbb.CreateVector(_o->float_arr) : 0;
  auto _vec3 = _o->vec3 ? CreateVec3Msg(_fbb, _o->vec3.get(), _rehasher) : 0;
  auto _vec4 = _o->vec4 ? CreateVec4Msg(_fbb, _o->vec4.get(), _rehasher) : 0;
  auto _vec3_arr = _o->vec3_arr.size() ? _fbb.CreateVector<::flatbuffers::Offset<Vec3Msg>> (_o->vec3_arr.size(), [](size_t i, _VectorArgs *__va) { return CreateVec3Msg(*__va->__fbb, __va->__o->vec3_arr[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _vec4_arr = _o->vec4_arr.size() ? _fbb.CreateVector<::flatbuffers::Offset<Vec4Msg>> (_o->vec4_arr.size(), [](size_t i, _VectorArgs *__va) { return CreateVec4Msg(*__va->__fbb, __va->__o->vec4_arr[i].get(), __va->__rehasher); }, &_va ) : 0;
  return CreateCommandMsg(
      _fbb,
      _name,
      _timestamp,
      _cmd_id,
      _sys_id,
      _int_val,
      _float_val,
      _int_arr,
      _float_arr,
      _vec3,
      _vec4,
      _vec3_arr,
      _vec4_arr);
}

inline const CommandMsg *GetCommandMsg(const void *buf) {
  return ::flatbuffers::GetRoot<CommandMsg>(buf);
}

inline const CommandMsg *GetSizePrefixedCommandMsg(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<CommandMsg>(buf);
}

inline const char *CommandMsgIdentifier() {
  return "CMD0";
}

inline bool CommandMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, CommandMsgIdentifier());
}

inline bool SizePrefixedCommandMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, CommandMsgIdentifier(), true);
}

inline bool VerifyCommandMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<CommandMsg>(CommandMsgIdentifier());
}

inline bool VerifySizePrefixedCommandMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<CommandMsg>(CommandMsgIdentifier());
}

inline void FinishCommandMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<CommandMsg> root) {
  fbb.Finish(root, CommandMsgIdentifier());
}

inline void FinishSizePrefixedCommandMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<CommandMsg> root) {
  fbb.FinishSizePrefixed(root, CommandMsgIdentifier());
}

inline std::unique_ptr<CommandMsgT> UnPackCommandMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<CommandMsgT>(GetCommandMsg(buf)->UnPack(res));
}

inline std::unique_ptr<CommandMsgT> UnPackSizePrefixedCommandMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<CommandMsgT>(GetSizePrefixedCommandMsg(buf)->UnPack(res));
}

#endif  // FLATBUFFERS_GENERATED_C000COMMANDS_H_
