// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_S004SRVOMRWALLMSG_H_
#define FLATBUFFERS_GENERATED_S004SRVOMRWALLMSG_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

struct Vec3Msg;
struct Vec3MsgBuilder;
struct Vec3MsgT;

struct Vec4Msg;
struct Vec4MsgBuilder;
struct Vec4MsgT;

struct SrvOMRWallMsg;
struct SrvOMRWallMsgBuilder;
struct SrvOMRWallMsgT;

struct Vec3MsgT : public ::flatbuffers::NativeTable {
  typedef Vec3Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
};

struct Vec3Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec3MsgT NativeTableType;
  typedef Vec3MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
  Vec3MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec3Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec3MsgBuilder {
  typedef Vec3Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec3Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec3Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec3Msg::VT_Z, z, 0.0f);
  }
  explicit Vec3MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec3Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec3Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f) {
  Vec3MsgBuilder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct Vec4MsgT : public ::flatbuffers::NativeTable {
  typedef Vec4Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
  float w = 0.0f;
};

struct Vec4Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec4MsgT NativeTableType;
  typedef Vec4MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8,
    VT_W = 10
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  float w() const {
    return GetField<float>(VT_W, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           VerifyField<float>(verifier, VT_W, 4) &&
           verifier.EndTable();
  }
  Vec4MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec4Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec4MsgBuilder {
  typedef Vec4Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec4Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec4Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec4Msg::VT_Z, z, 0.0f);
  }
  void add_w(float w) {
    fbb_.AddElement<float>(Vec4Msg::VT_W, w, 0.0f);
  }
  explicit Vec4MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec4Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec4Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f,
    float w = 0.0f) {
  Vec4MsgBuilder builder_(_fbb);
  builder_.add_w(w);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SrvOMRWallMsgT : public ::flatbuffers::NativeTable {
  typedef SrvOMRWallMsg TableType;
  double timestamp = 0.0;
  std::string name{};
  uint32_t sys_id = 0;
  uint32_t req_src_id = 0;
  bool clear_wall = false;
  bool set_wall = false;
  std::vector<std::unique_ptr<Vec3MsgT>> vec3_list{};
  SrvOMRWallMsgT() = default;
  SrvOMRWallMsgT(const SrvOMRWallMsgT &o);
  SrvOMRWallMsgT(SrvOMRWallMsgT&&) FLATBUFFERS_NOEXCEPT = default;
  SrvOMRWallMsgT &operator=(SrvOMRWallMsgT o) FLATBUFFERS_NOEXCEPT;
};

struct SrvOMRWallMsg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SrvOMRWallMsgT NativeTableType;
  typedef SrvOMRWallMsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_NAME = 6,
    VT_SYS_ID = 8,
    VT_REQ_SRC_ID = 10,
    VT_CLEAR_WALL = 12,
    VT_SET_WALL = 14,
    VT_VEC3_LIST = 16
  };
  double timestamp() const {
    return GetField<double>(VT_TIMESTAMP, 0.0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint32_t sys_id() const {
    return GetField<uint32_t>(VT_SYS_ID, 0);
  }
  uint32_t req_src_id() const {
    return GetField<uint32_t>(VT_REQ_SRC_ID, 0);
  }
  bool clear_wall() const {
    return GetField<uint8_t>(VT_CLEAR_WALL, 0) != 0;
  }
  bool set_wall() const {
    return GetField<uint8_t>(VT_SET_WALL, 0) != 0;
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Vec3Msg>> *vec3_list() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Vec3Msg>> *>(VT_VEC3_LIST);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_TIMESTAMP, 8) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint32_t>(verifier, VT_SYS_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_REQ_SRC_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_CLEAR_WALL, 1) &&
           VerifyField<uint8_t>(verifier, VT_SET_WALL, 1) &&
           VerifyOffset(verifier, VT_VEC3_LIST) &&
           verifier.VerifyVector(vec3_list()) &&
           verifier.VerifyVectorOfTables(vec3_list()) &&
           verifier.EndTable();
  }
  SrvOMRWallMsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SrvOMRWallMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SrvOMRWallMsg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SrvOMRWallMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SrvOMRWallMsgBuilder {
  typedef SrvOMRWallMsg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(double timestamp) {
    fbb_.AddElement<double>(SrvOMRWallMsg::VT_TIMESTAMP, timestamp, 0.0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(SrvOMRWallMsg::VT_NAME, name);
  }
  void add_sys_id(uint32_t sys_id) {
    fbb_.AddElement<uint32_t>(SrvOMRWallMsg::VT_SYS_ID, sys_id, 0);
  }
  void add_req_src_id(uint32_t req_src_id) {
    fbb_.AddElement<uint32_t>(SrvOMRWallMsg::VT_REQ_SRC_ID, req_src_id, 0);
  }
  void add_clear_wall(bool clear_wall) {
    fbb_.AddElement<uint8_t>(SrvOMRWallMsg::VT_CLEAR_WALL, static_cast<uint8_t>(clear_wall), 0);
  }
  void add_set_wall(bool set_wall) {
    fbb_.AddElement<uint8_t>(SrvOMRWallMsg::VT_SET_WALL, static_cast<uint8_t>(set_wall), 0);
  }
  void add_vec3_list(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Vec3Msg>>> vec3_list) {
    fbb_.AddOffset(SrvOMRWallMsg::VT_VEC3_LIST, vec3_list);
  }
  explicit SrvOMRWallMsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SrvOMRWallMsg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SrvOMRWallMsg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SrvOMRWallMsg> CreateSrvOMRWallMsg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double timestamp = 0.0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint32_t sys_id = 0,
    uint32_t req_src_id = 0,
    bool clear_wall = false,
    bool set_wall = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Vec3Msg>>> vec3_list = 0) {
  SrvOMRWallMsgBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_vec3_list(vec3_list);
  builder_.add_req_src_id(req_src_id);
  builder_.add_sys_id(sys_id);
  builder_.add_name(name);
  builder_.add_set_wall(set_wall);
  builder_.add_clear_wall(clear_wall);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SrvOMRWallMsg> CreateSrvOMRWallMsgDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double timestamp = 0.0,
    const char *name = nullptr,
    uint32_t sys_id = 0,
    uint32_t req_src_id = 0,
    bool clear_wall = false,
    bool set_wall = false,
    const std::vector<::flatbuffers::Offset<Vec3Msg>> *vec3_list = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto vec3_list__ = vec3_list ? _fbb.CreateVector<::flatbuffers::Offset<Vec3Msg>>(*vec3_list) : 0;
  return CreateSrvOMRWallMsg(
      _fbb,
      timestamp,
      name__,
      sys_id,
      req_src_id,
      clear_wall,
      set_wall,
      vec3_list__);
}

::flatbuffers::Offset<SrvOMRWallMsg> CreateSrvOMRWallMsg(::flatbuffers::FlatBufferBuilder &_fbb, const SrvOMRWallMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline Vec3MsgT *Vec3Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec3MsgT>(new Vec3MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec3Msg::UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
}

inline ::flatbuffers::Offset<Vec3Msg> Vec3Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec3Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec3MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  return CreateVec3Msg(
      _fbb,
      _x,
      _y,
      _z);
}

inline Vec4MsgT *Vec4Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec4MsgT>(new Vec4MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec4Msg::UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
  { auto _e = w(); _o->w = _e; }
}

inline ::flatbuffers::Offset<Vec4Msg> Vec4Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec4Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec4MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  auto _w = _o->w;
  return CreateVec4Msg(
      _fbb,
      _x,
      _y,
      _z,
      _w);
}

inline SrvOMRWallMsgT::SrvOMRWallMsgT(const SrvOMRWallMsgT &o)
      : timestamp(o.timestamp),
        name(o.name),
        sys_id(o.sys_id),
        req_src_id(o.req_src_id),
        clear_wall(o.clear_wall),
        set_wall(o.set_wall) {
  vec3_list.reserve(o.vec3_list.size());
  for (const auto &vec3_list_ : o.vec3_list) { vec3_list.emplace_back((vec3_list_) ? new Vec3MsgT(*vec3_list_) : nullptr); }
}

inline SrvOMRWallMsgT &SrvOMRWallMsgT::operator=(SrvOMRWallMsgT o) FLATBUFFERS_NOEXCEPT {
  std::swap(timestamp, o.timestamp);
  std::swap(name, o.name);
  std::swap(sys_id, o.sys_id);
  std::swap(req_src_id, o.req_src_id);
  std::swap(clear_wall, o.clear_wall);
  std::swap(set_wall, o.set_wall);
  std::swap(vec3_list, o.vec3_list);
  return *this;
}

inline SrvOMRWallMsgT *SrvOMRWallMsg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SrvOMRWallMsgT>(new SrvOMRWallMsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SrvOMRWallMsg::UnPackTo(SrvOMRWallMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = timestamp(); _o->timestamp = _e; }
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = sys_id(); _o->sys_id = _e; }
  { auto _e = req_src_id(); _o->req_src_id = _e; }
  { auto _e = clear_wall(); _o->clear_wall = _e; }
  { auto _e = set_wall(); _o->set_wall = _e; }
  { auto _e = vec3_list(); if (_e) { _o->vec3_list.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->vec3_list[_i]) { _e->Get(_i)->UnPackTo(_o->vec3_list[_i].get(), _resolver); } else { _o->vec3_list[_i] = std::unique_ptr<Vec3MsgT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->vec3_list.resize(0); } }
}

inline ::flatbuffers::Offset<SrvOMRWallMsg> SrvOMRWallMsg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SrvOMRWallMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSrvOMRWallMsg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SrvOMRWallMsg> CreateSrvOMRWallMsg(::flatbuffers::FlatBufferBuilder &_fbb, const SrvOMRWallMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SrvOMRWallMsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _timestamp = _o->timestamp;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _sys_id = _o->sys_id;
  auto _req_src_id = _o->req_src_id;
  auto _clear_wall = _o->clear_wall;
  auto _set_wall = _o->set_wall;
  auto _vec3_list = _o->vec3_list.size() ? _fbb.CreateVector<::flatbuffers::Offset<Vec3Msg>> (_o->vec3_list.size(), [](size_t i, _VectorArgs *__va) { return CreateVec3Msg(*__va->__fbb, __va->__o->vec3_list[i].get(), __va->__rehasher); }, &_va ) : 0;
  return CreateSrvOMRWallMsg(
      _fbb,
      _timestamp,
      _name,
      _sys_id,
      _req_src_id,
      _clear_wall,
      _set_wall,
      _vec3_list);
}

inline const SrvOMRWallMsg *GetSrvOMRWallMsg(const void *buf) {
  return ::flatbuffers::GetRoot<SrvOMRWallMsg>(buf);
}

inline const SrvOMRWallMsg *GetSizePrefixedSrvOMRWallMsg(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SrvOMRWallMsg>(buf);
}

inline const char *SrvOMRWallMsgIdentifier() {
  return "S004";
}

inline bool SrvOMRWallMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SrvOMRWallMsgIdentifier());
}

inline bool SizePrefixedSrvOMRWallMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SrvOMRWallMsgIdentifier(), true);
}

inline bool VerifySrvOMRWallMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SrvOMRWallMsg>(SrvOMRWallMsgIdentifier());
}

inline bool VerifySizePrefixedSrvOMRWallMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SrvOMRWallMsg>(SrvOMRWallMsgIdentifier());
}

inline void FinishSrvOMRWallMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SrvOMRWallMsg> root) {
  fbb.Finish(root, SrvOMRWallMsgIdentifier());
}

inline void FinishSizePrefixedSrvOMRWallMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SrvOMRWallMsg> root) {
  fbb.FinishSizePrefixed(root, SrvOMRWallMsgIdentifier());
}

inline std::unique_ptr<SrvOMRWallMsgT> UnPackSrvOMRWallMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SrvOMRWallMsgT>(GetSrvOMRWallMsg(buf)->UnPack(res));
}

inline std::unique_ptr<SrvOMRWallMsgT> UnPackSizePrefixedSrvOMRWallMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SrvOMRWallMsgT>(GetSizePrefixedSrvOMRWallMsg(buf)->UnPack(res));
}

#endif  // FLATBUFFERS_GENERATED_S004SRVOMRWALLMSG_H_
