// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_S003SRVSIMPARAMSMSG_H_
#define FLATBUFFERS_GENERATED_S003SRVSIMPARAMSMSG_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

struct Vec3Msg;
struct Vec3MsgBuilder;
struct Vec3MsgT;

struct Vec4Msg;
struct Vec4MsgBuilder;
struct Vec4MsgT;

struct SrvSimParamsMsg;
struct SrvSimParamsMsgBuilder;
struct SrvSimParamsMsgT;

struct Vec3MsgT : public ::flatbuffers::NativeTable {
  typedef Vec3Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
};

struct Vec3Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec3MsgT NativeTableType;
  typedef Vec3MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
  Vec3MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec3Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec3MsgBuilder {
  typedef Vec3Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec3Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec3Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec3Msg::VT_Z, z, 0.0f);
  }
  explicit Vec3MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec3Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec3Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f) {
  Vec3MsgBuilder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct Vec4MsgT : public ::flatbuffers::NativeTable {
  typedef Vec4Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
  float w = 0.0f;
};

struct Vec4Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec4MsgT NativeTableType;
  typedef Vec4MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8,
    VT_W = 10
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  float w() const {
    return GetField<float>(VT_W, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           VerifyField<float>(verifier, VT_W, 4) &&
           verifier.EndTable();
  }
  Vec4MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec4Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec4MsgBuilder {
  typedef Vec4Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec4Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec4Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec4Msg::VT_Z, z, 0.0f);
  }
  void add_w(float w) {
    fbb_.AddElement<float>(Vec4Msg::VT_W, w, 0.0f);
  }
  explicit Vec4MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec4Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec4Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f,
    float w = 0.0f) {
  Vec4MsgBuilder builder_(_fbb);
  builder_.add_w(w);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SrvSimParamsMsgT : public ::flatbuffers::NativeTable {
  typedef SrvSimParamsMsg TableType;
  double timestamp = 0.0;
  std::string name{};
  uint32_t sys_id = 0;
  uint32_t req_src_id = 0;
  int32_t cmd_report_once = 0;
  int32_t stream_to_rjs = 0;
  int32_t stream_to_ws = 0;
  int32_t noise_on = 0;
  int32_t img_resolution = 0;
  int32_t set_stream_to_rjs = 0;
  int32_t set_stream_to_ws = 0;
  int32_t set_noise_on = 0;
  int32_t set_img_resolution = 0;
};

struct SrvSimParamsMsg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SrvSimParamsMsgT NativeTableType;
  typedef SrvSimParamsMsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_NAME = 6,
    VT_SYS_ID = 8,
    VT_REQ_SRC_ID = 10,
    VT_CMD_REPORT_ONCE = 12,
    VT_STREAM_TO_RJS = 14,
    VT_STREAM_TO_WS = 16,
    VT_NOISE_ON = 18,
    VT_IMG_RESOLUTION = 20,
    VT_SET_STREAM_TO_RJS = 22,
    VT_SET_STREAM_TO_WS = 24,
    VT_SET_NOISE_ON = 26,
    VT_SET_IMG_RESOLUTION = 28
  };
  double timestamp() const {
    return GetField<double>(VT_TIMESTAMP, 0.0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint32_t sys_id() const {
    return GetField<uint32_t>(VT_SYS_ID, 0);
  }
  uint32_t req_src_id() const {
    return GetField<uint32_t>(VT_REQ_SRC_ID, 0);
  }
  int32_t cmd_report_once() const {
    return GetField<int32_t>(VT_CMD_REPORT_ONCE, 0);
  }
  int32_t stream_to_rjs() const {
    return GetField<int32_t>(VT_STREAM_TO_RJS, 0);
  }
  int32_t stream_to_ws() const {
    return GetField<int32_t>(VT_STREAM_TO_WS, 0);
  }
  int32_t noise_on() const {
    return GetField<int32_t>(VT_NOISE_ON, 0);
  }
  int32_t img_resolution() const {
    return GetField<int32_t>(VT_IMG_RESOLUTION, 0);
  }
  int32_t set_stream_to_rjs() const {
    return GetField<int32_t>(VT_SET_STREAM_TO_RJS, 0);
  }
  int32_t set_stream_to_ws() const {
    return GetField<int32_t>(VT_SET_STREAM_TO_WS, 0);
  }
  int32_t set_noise_on() const {
    return GetField<int32_t>(VT_SET_NOISE_ON, 0);
  }
  int32_t set_img_resolution() const {
    return GetField<int32_t>(VT_SET_IMG_RESOLUTION, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_TIMESTAMP, 8) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint32_t>(verifier, VT_SYS_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_REQ_SRC_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_CMD_REPORT_ONCE, 4) &&
           VerifyField<int32_t>(verifier, VT_STREAM_TO_RJS, 4) &&
           VerifyField<int32_t>(verifier, VT_STREAM_TO_WS, 4) &&
           VerifyField<int32_t>(verifier, VT_NOISE_ON, 4) &&
           VerifyField<int32_t>(verifier, VT_IMG_RESOLUTION, 4) &&
           VerifyField<int32_t>(verifier, VT_SET_STREAM_TO_RJS, 4) &&
           VerifyField<int32_t>(verifier, VT_SET_STREAM_TO_WS, 4) &&
           VerifyField<int32_t>(verifier, VT_SET_NOISE_ON, 4) &&
           VerifyField<int32_t>(verifier, VT_SET_IMG_RESOLUTION, 4) &&
           verifier.EndTable();
  }
  SrvSimParamsMsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SrvSimParamsMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SrvSimParamsMsg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SrvSimParamsMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SrvSimParamsMsgBuilder {
  typedef SrvSimParamsMsg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(double timestamp) {
    fbb_.AddElement<double>(SrvSimParamsMsg::VT_TIMESTAMP, timestamp, 0.0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(SrvSimParamsMsg::VT_NAME, name);
  }
  void add_sys_id(uint32_t sys_id) {
    fbb_.AddElement<uint32_t>(SrvSimParamsMsg::VT_SYS_ID, sys_id, 0);
  }
  void add_req_src_id(uint32_t req_src_id) {
    fbb_.AddElement<uint32_t>(SrvSimParamsMsg::VT_REQ_SRC_ID, req_src_id, 0);
  }
  void add_cmd_report_once(int32_t cmd_report_once) {
    fbb_.AddElement<int32_t>(SrvSimParamsMsg::VT_CMD_REPORT_ONCE, cmd_report_once, 0);
  }
  void add_stream_to_rjs(int32_t stream_to_rjs) {
    fbb_.AddElement<int32_t>(SrvSimParamsMsg::VT_STREAM_TO_RJS, stream_to_rjs, 0);
  }
  void add_stream_to_ws(int32_t stream_to_ws) {
    fbb_.AddElement<int32_t>(SrvSimParamsMsg::VT_STREAM_TO_WS, stream_to_ws, 0);
  }
  void add_noise_on(int32_t noise_on) {
    fbb_.AddElement<int32_t>(SrvSimParamsMsg::VT_NOISE_ON, noise_on, 0);
  }
  void add_img_resolution(int32_t img_resolution) {
    fbb_.AddElement<int32_t>(SrvSimParamsMsg::VT_IMG_RESOLUTION, img_resolution, 0);
  }
  void add_set_stream_to_rjs(int32_t set_stream_to_rjs) {
    fbb_.AddElement<int32_t>(SrvSimParamsMsg::VT_SET_STREAM_TO_RJS, set_stream_to_rjs, 0);
  }
  void add_set_stream_to_ws(int32_t set_stream_to_ws) {
    fbb_.AddElement<int32_t>(SrvSimParamsMsg::VT_SET_STREAM_TO_WS, set_stream_to_ws, 0);
  }
  void add_set_noise_on(int32_t set_noise_on) {
    fbb_.AddElement<int32_t>(SrvSimParamsMsg::VT_SET_NOISE_ON, set_noise_on, 0);
  }
  void add_set_img_resolution(int32_t set_img_resolution) {
    fbb_.AddElement<int32_t>(SrvSimParamsMsg::VT_SET_IMG_RESOLUTION, set_img_resolution, 0);
  }
  explicit SrvSimParamsMsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SrvSimParamsMsg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SrvSimParamsMsg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SrvSimParamsMsg> CreateSrvSimParamsMsg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double timestamp = 0.0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint32_t sys_id = 0,
    uint32_t req_src_id = 0,
    int32_t cmd_report_once = 0,
    int32_t stream_to_rjs = 0,
    int32_t stream_to_ws = 0,
    int32_t noise_on = 0,
    int32_t img_resolution = 0,
    int32_t set_stream_to_rjs = 0,
    int32_t set_stream_to_ws = 0,
    int32_t set_noise_on = 0,
    int32_t set_img_resolution = 0) {
  SrvSimParamsMsgBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_set_img_resolution(set_img_resolution);
  builder_.add_set_noise_on(set_noise_on);
  builder_.add_set_stream_to_ws(set_stream_to_ws);
  builder_.add_set_stream_to_rjs(set_stream_to_rjs);
  builder_.add_img_resolution(img_resolution);
  builder_.add_noise_on(noise_on);
  builder_.add_stream_to_ws(stream_to_ws);
  builder_.add_stream_to_rjs(stream_to_rjs);
  builder_.add_cmd_report_once(cmd_report_once);
  builder_.add_req_src_id(req_src_id);
  builder_.add_sys_id(sys_id);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SrvSimParamsMsg> CreateSrvSimParamsMsgDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double timestamp = 0.0,
    const char *name = nullptr,
    uint32_t sys_id = 0,
    uint32_t req_src_id = 0,
    int32_t cmd_report_once = 0,
    int32_t stream_to_rjs = 0,
    int32_t stream_to_ws = 0,
    int32_t noise_on = 0,
    int32_t img_resolution = 0,
    int32_t set_stream_to_rjs = 0,
    int32_t set_stream_to_ws = 0,
    int32_t set_noise_on = 0,
    int32_t set_img_resolution = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return CreateSrvSimParamsMsg(
      _fbb,
      timestamp,
      name__,
      sys_id,
      req_src_id,
      cmd_report_once,
      stream_to_rjs,
      stream_to_ws,
      noise_on,
      img_resolution,
      set_stream_to_rjs,
      set_stream_to_ws,
      set_noise_on,
      set_img_resolution);
}

::flatbuffers::Offset<SrvSimParamsMsg> CreateSrvSimParamsMsg(::flatbuffers::FlatBufferBuilder &_fbb, const SrvSimParamsMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline Vec3MsgT *Vec3Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec3MsgT>(new Vec3MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec3Msg::UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
}

inline ::flatbuffers::Offset<Vec3Msg> Vec3Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec3Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec3MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  return CreateVec3Msg(
      _fbb,
      _x,
      _y,
      _z);
}

inline Vec4MsgT *Vec4Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec4MsgT>(new Vec4MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec4Msg::UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
  { auto _e = w(); _o->w = _e; }
}

inline ::flatbuffers::Offset<Vec4Msg> Vec4Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec4Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec4MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  auto _w = _o->w;
  return CreateVec4Msg(
      _fbb,
      _x,
      _y,
      _z,
      _w);
}

inline SrvSimParamsMsgT *SrvSimParamsMsg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SrvSimParamsMsgT>(new SrvSimParamsMsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SrvSimParamsMsg::UnPackTo(SrvSimParamsMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = timestamp(); _o->timestamp = _e; }
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = sys_id(); _o->sys_id = _e; }
  { auto _e = req_src_id(); _o->req_src_id = _e; }
  { auto _e = cmd_report_once(); _o->cmd_report_once = _e; }
  { auto _e = stream_to_rjs(); _o->stream_to_rjs = _e; }
  { auto _e = stream_to_ws(); _o->stream_to_ws = _e; }
  { auto _e = noise_on(); _o->noise_on = _e; }
  { auto _e = img_resolution(); _o->img_resolution = _e; }
  { auto _e = set_stream_to_rjs(); _o->set_stream_to_rjs = _e; }
  { auto _e = set_stream_to_ws(); _o->set_stream_to_ws = _e; }
  { auto _e = set_noise_on(); _o->set_noise_on = _e; }
  { auto _e = set_img_resolution(); _o->set_img_resolution = _e; }
}

inline ::flatbuffers::Offset<SrvSimParamsMsg> SrvSimParamsMsg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SrvSimParamsMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSrvSimParamsMsg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SrvSimParamsMsg> CreateSrvSimParamsMsg(::flatbuffers::FlatBufferBuilder &_fbb, const SrvSimParamsMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SrvSimParamsMsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _timestamp = _o->timestamp;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _sys_id = _o->sys_id;
  auto _req_src_id = _o->req_src_id;
  auto _cmd_report_once = _o->cmd_report_once;
  auto _stream_to_rjs = _o->stream_to_rjs;
  auto _stream_to_ws = _o->stream_to_ws;
  auto _noise_on = _o->noise_on;
  auto _img_resolution = _o->img_resolution;
  auto _set_stream_to_rjs = _o->set_stream_to_rjs;
  auto _set_stream_to_ws = _o->set_stream_to_ws;
  auto _set_noise_on = _o->set_noise_on;
  auto _set_img_resolution = _o->set_img_resolution;
  return CreateSrvSimParamsMsg(
      _fbb,
      _timestamp,
      _name,
      _sys_id,
      _req_src_id,
      _cmd_report_once,
      _stream_to_rjs,
      _stream_to_ws,
      _noise_on,
      _img_resolution,
      _set_stream_to_rjs,
      _set_stream_to_ws,
      _set_noise_on,
      _set_img_resolution);
}

inline const SrvSimParamsMsg *GetSrvSimParamsMsg(const void *buf) {
  return ::flatbuffers::GetRoot<SrvSimParamsMsg>(buf);
}

inline const SrvSimParamsMsg *GetSizePrefixedSrvSimParamsMsg(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SrvSimParamsMsg>(buf);
}

inline const char *SrvSimParamsMsgIdentifier() {
  return "S003";
}

inline bool SrvSimParamsMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SrvSimParamsMsgIdentifier());
}

inline bool SizePrefixedSrvSimParamsMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SrvSimParamsMsgIdentifier(), true);
}

inline bool VerifySrvSimParamsMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SrvSimParamsMsg>(SrvSimParamsMsgIdentifier());
}

inline bool VerifySizePrefixedSrvSimParamsMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SrvSimParamsMsg>(SrvSimParamsMsgIdentifier());
}

inline void FinishSrvSimParamsMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SrvSimParamsMsg> root) {
  fbb.Finish(root, SrvSimParamsMsgIdentifier());
}

inline void FinishSizePrefixedSrvSimParamsMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SrvSimParamsMsg> root) {
  fbb.FinishSizePrefixed(root, SrvSimParamsMsgIdentifier());
}

inline std::unique_ptr<SrvSimParamsMsgT> UnPackSrvSimParamsMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SrvSimParamsMsgT>(GetSrvSimParamsMsg(buf)->UnPack(res));
}

inline std::unique_ptr<SrvSimParamsMsgT> UnPackSizePrefixedSrvSimParamsMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SrvSimParamsMsgT>(GetSizePrefixedSrvSimParamsMsg(buf)->UnPack(res));
}

#endif  // FLATBUFFERS_GENERATED_S003SRVSIMPARAMSMSG_H_
