// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_S001SRVGLOBALPARAMSMSG_H_
#define FLATBUFFERS_GENERATED_S001SRVGLOBALPARAMSMSG_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

struct Vec3Msg;
struct Vec3MsgBuilder;
struct Vec3MsgT;

struct Vec4Msg;
struct Vec4MsgBuilder;
struct Vec4MsgT;

struct SrvGlobalParamsMsg;
struct SrvGlobalParamsMsgBuilder;
struct SrvGlobalParamsMsgT;

struct Vec3MsgT : public ::flatbuffers::NativeTable {
  typedef Vec3Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
};

struct Vec3Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec3MsgT NativeTableType;
  typedef Vec3MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
  Vec3MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec3Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec3MsgBuilder {
  typedef Vec3Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec3Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec3Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec3Msg::VT_Z, z, 0.0f);
  }
  explicit Vec3MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec3Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec3Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f) {
  Vec3MsgBuilder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct Vec4MsgT : public ::flatbuffers::NativeTable {
  typedef Vec4Msg TableType;
  float x = 0.0f;
  float y = 0.0f;
  float z = 0.0f;
  float w = 0.0f;
};

struct Vec4Msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec4MsgT NativeTableType;
  typedef Vec4MsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8,
    VT_W = 10
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  float w() const {
    return GetField<float>(VT_W, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           VerifyField<float>(verifier, VT_W, 4) &&
           verifier.EndTable();
  }
  Vec4MsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Vec4Msg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Vec4MsgBuilder {
  typedef Vec4Msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec4Msg::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec4Msg::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec4Msg::VT_Z, z, 0.0f);
  }
  void add_w(float w) {
    fbb_.AddElement<float>(Vec4Msg::VT_W, w, 0.0f);
  }
  explicit Vec4MsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec4Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec4Msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f,
    float w = 0.0f) {
  Vec4MsgBuilder builder_(_fbb);
  builder_.add_w(w);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SrvGlobalParamsMsgT : public ::flatbuffers::NativeTable {
  typedef SrvGlobalParamsMsg TableType;
  double timestamp = 0.0;
  std::string name{};
  uint32_t sys_id = 0;
  uint32_t req_src_id = 0;
  std::string scene{};
  int32_t cmd_report_once = 0;
  int32_t is_signed = 0;
  int32_t input_breaker = 0;
  int32_t player_mode = 0;
  std::string set_scene{};
  std::string set_signiture{};
  int32_t set_input_breaker = 0;
  int32_t set_player_mode = 0;
};

struct SrvGlobalParamsMsg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SrvGlobalParamsMsgT NativeTableType;
  typedef SrvGlobalParamsMsgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_NAME = 6,
    VT_SYS_ID = 8,
    VT_REQ_SRC_ID = 10,
    VT_SCENE = 12,
    VT_CMD_REPORT_ONCE = 14,
    VT_IS_SIGNED = 16,
    VT_INPUT_BREAKER = 18,
    VT_PLAYER_MODE = 20,
    VT_SET_SCENE = 22,
    VT_SET_SIGNITURE = 24,
    VT_SET_INPUT_BREAKER = 26,
    VT_SET_PLAYER_MODE = 28
  };
  double timestamp() const {
    return GetField<double>(VT_TIMESTAMP, 0.0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint32_t sys_id() const {
    return GetField<uint32_t>(VT_SYS_ID, 0);
  }
  uint32_t req_src_id() const {
    return GetField<uint32_t>(VT_REQ_SRC_ID, 0);
  }
  const ::flatbuffers::String *scene() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SCENE);
  }
  int32_t cmd_report_once() const {
    return GetField<int32_t>(VT_CMD_REPORT_ONCE, 0);
  }
  int32_t is_signed() const {
    return GetField<int32_t>(VT_IS_SIGNED, 0);
  }
  int32_t input_breaker() const {
    return GetField<int32_t>(VT_INPUT_BREAKER, 0);
  }
  int32_t player_mode() const {
    return GetField<int32_t>(VT_PLAYER_MODE, 0);
  }
  const ::flatbuffers::String *set_scene() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SET_SCENE);
  }
  const ::flatbuffers::String *set_signiture() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SET_SIGNITURE);
  }
  int32_t set_input_breaker() const {
    return GetField<int32_t>(VT_SET_INPUT_BREAKER, 0);
  }
  int32_t set_player_mode() const {
    return GetField<int32_t>(VT_SET_PLAYER_MODE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_TIMESTAMP, 8) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint32_t>(verifier, VT_SYS_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_REQ_SRC_ID, 4) &&
           VerifyOffset(verifier, VT_SCENE) &&
           verifier.VerifyString(scene()) &&
           VerifyField<int32_t>(verifier, VT_CMD_REPORT_ONCE, 4) &&
           VerifyField<int32_t>(verifier, VT_IS_SIGNED, 4) &&
           VerifyField<int32_t>(verifier, VT_INPUT_BREAKER, 4) &&
           VerifyField<int32_t>(verifier, VT_PLAYER_MODE, 4) &&
           VerifyOffset(verifier, VT_SET_SCENE) &&
           verifier.VerifyString(set_scene()) &&
           VerifyOffset(verifier, VT_SET_SIGNITURE) &&
           verifier.VerifyString(set_signiture()) &&
           VerifyField<int32_t>(verifier, VT_SET_INPUT_BREAKER, 4) &&
           VerifyField<int32_t>(verifier, VT_SET_PLAYER_MODE, 4) &&
           verifier.EndTable();
  }
  SrvGlobalParamsMsgT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SrvGlobalParamsMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SrvGlobalParamsMsg> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SrvGlobalParamsMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SrvGlobalParamsMsgBuilder {
  typedef SrvGlobalParamsMsg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(double timestamp) {
    fbb_.AddElement<double>(SrvGlobalParamsMsg::VT_TIMESTAMP, timestamp, 0.0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(SrvGlobalParamsMsg::VT_NAME, name);
  }
  void add_sys_id(uint32_t sys_id) {
    fbb_.AddElement<uint32_t>(SrvGlobalParamsMsg::VT_SYS_ID, sys_id, 0);
  }
  void add_req_src_id(uint32_t req_src_id) {
    fbb_.AddElement<uint32_t>(SrvGlobalParamsMsg::VT_REQ_SRC_ID, req_src_id, 0);
  }
  void add_scene(::flatbuffers::Offset<::flatbuffers::String> scene) {
    fbb_.AddOffset(SrvGlobalParamsMsg::VT_SCENE, scene);
  }
  void add_cmd_report_once(int32_t cmd_report_once) {
    fbb_.AddElement<int32_t>(SrvGlobalParamsMsg::VT_CMD_REPORT_ONCE, cmd_report_once, 0);
  }
  void add_is_signed(int32_t is_signed) {
    fbb_.AddElement<int32_t>(SrvGlobalParamsMsg::VT_IS_SIGNED, is_signed, 0);
  }
  void add_input_breaker(int32_t input_breaker) {
    fbb_.AddElement<int32_t>(SrvGlobalParamsMsg::VT_INPUT_BREAKER, input_breaker, 0);
  }
  void add_player_mode(int32_t player_mode) {
    fbb_.AddElement<int32_t>(SrvGlobalParamsMsg::VT_PLAYER_MODE, player_mode, 0);
  }
  void add_set_scene(::flatbuffers::Offset<::flatbuffers::String> set_scene) {
    fbb_.AddOffset(SrvGlobalParamsMsg::VT_SET_SCENE, set_scene);
  }
  void add_set_signiture(::flatbuffers::Offset<::flatbuffers::String> set_signiture) {
    fbb_.AddOffset(SrvGlobalParamsMsg::VT_SET_SIGNITURE, set_signiture);
  }
  void add_set_input_breaker(int32_t set_input_breaker) {
    fbb_.AddElement<int32_t>(SrvGlobalParamsMsg::VT_SET_INPUT_BREAKER, set_input_breaker, 0);
  }
  void add_set_player_mode(int32_t set_player_mode) {
    fbb_.AddElement<int32_t>(SrvGlobalParamsMsg::VT_SET_PLAYER_MODE, set_player_mode, 0);
  }
  explicit SrvGlobalParamsMsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SrvGlobalParamsMsg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SrvGlobalParamsMsg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SrvGlobalParamsMsg> CreateSrvGlobalParamsMsg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double timestamp = 0.0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint32_t sys_id = 0,
    uint32_t req_src_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> scene = 0,
    int32_t cmd_report_once = 0,
    int32_t is_signed = 0,
    int32_t input_breaker = 0,
    int32_t player_mode = 0,
    ::flatbuffers::Offset<::flatbuffers::String> set_scene = 0,
    ::flatbuffers::Offset<::flatbuffers::String> set_signiture = 0,
    int32_t set_input_breaker = 0,
    int32_t set_player_mode = 0) {
  SrvGlobalParamsMsgBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_set_player_mode(set_player_mode);
  builder_.add_set_input_breaker(set_input_breaker);
  builder_.add_set_signiture(set_signiture);
  builder_.add_set_scene(set_scene);
  builder_.add_player_mode(player_mode);
  builder_.add_input_breaker(input_breaker);
  builder_.add_is_signed(is_signed);
  builder_.add_cmd_report_once(cmd_report_once);
  builder_.add_scene(scene);
  builder_.add_req_src_id(req_src_id);
  builder_.add_sys_id(sys_id);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SrvGlobalParamsMsg> CreateSrvGlobalParamsMsgDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double timestamp = 0.0,
    const char *name = nullptr,
    uint32_t sys_id = 0,
    uint32_t req_src_id = 0,
    const char *scene = nullptr,
    int32_t cmd_report_once = 0,
    int32_t is_signed = 0,
    int32_t input_breaker = 0,
    int32_t player_mode = 0,
    const char *set_scene = nullptr,
    const char *set_signiture = nullptr,
    int32_t set_input_breaker = 0,
    int32_t set_player_mode = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto scene__ = scene ? _fbb.CreateString(scene) : 0;
  auto set_scene__ = set_scene ? _fbb.CreateString(set_scene) : 0;
  auto set_signiture__ = set_signiture ? _fbb.CreateString(set_signiture) : 0;
  return CreateSrvGlobalParamsMsg(
      _fbb,
      timestamp,
      name__,
      sys_id,
      req_src_id,
      scene__,
      cmd_report_once,
      is_signed,
      input_breaker,
      player_mode,
      set_scene__,
      set_signiture__,
      set_input_breaker,
      set_player_mode);
}

::flatbuffers::Offset<SrvGlobalParamsMsg> CreateSrvGlobalParamsMsg(::flatbuffers::FlatBufferBuilder &_fbb, const SrvGlobalParamsMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline Vec3MsgT *Vec3Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec3MsgT>(new Vec3MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec3Msg::UnPackTo(Vec3MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
}

inline ::flatbuffers::Offset<Vec3Msg> Vec3Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec3Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec3Msg> CreateVec3Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec3MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec3MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  return CreateVec3Msg(
      _fbb,
      _x,
      _y,
      _z);
}

inline Vec4MsgT *Vec4Msg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Vec4MsgT>(new Vec4MsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Vec4Msg::UnPackTo(Vec4MsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = z(); _o->z = _e; }
  { auto _e = w(); _o->w = _e; }
}

inline ::flatbuffers::Offset<Vec4Msg> Vec4Msg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVec4Msg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Vec4Msg> CreateVec4Msg(::flatbuffers::FlatBufferBuilder &_fbb, const Vec4MsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Vec4MsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _z = _o->z;
  auto _w = _o->w;
  return CreateVec4Msg(
      _fbb,
      _x,
      _y,
      _z,
      _w);
}

inline SrvGlobalParamsMsgT *SrvGlobalParamsMsg::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SrvGlobalParamsMsgT>(new SrvGlobalParamsMsgT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SrvGlobalParamsMsg::UnPackTo(SrvGlobalParamsMsgT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = timestamp(); _o->timestamp = _e; }
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = sys_id(); _o->sys_id = _e; }
  { auto _e = req_src_id(); _o->req_src_id = _e; }
  { auto _e = scene(); if (_e) _o->scene = _e->str(); }
  { auto _e = cmd_report_once(); _o->cmd_report_once = _e; }
  { auto _e = is_signed(); _o->is_signed = _e; }
  { auto _e = input_breaker(); _o->input_breaker = _e; }
  { auto _e = player_mode(); _o->player_mode = _e; }
  { auto _e = set_scene(); if (_e) _o->set_scene = _e->str(); }
  { auto _e = set_signiture(); if (_e) _o->set_signiture = _e->str(); }
  { auto _e = set_input_breaker(); _o->set_input_breaker = _e; }
  { auto _e = set_player_mode(); _o->set_player_mode = _e; }
}

inline ::flatbuffers::Offset<SrvGlobalParamsMsg> SrvGlobalParamsMsg::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SrvGlobalParamsMsgT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSrvGlobalParamsMsg(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SrvGlobalParamsMsg> CreateSrvGlobalParamsMsg(::flatbuffers::FlatBufferBuilder &_fbb, const SrvGlobalParamsMsgT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SrvGlobalParamsMsgT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _timestamp = _o->timestamp;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _sys_id = _o->sys_id;
  auto _req_src_id = _o->req_src_id;
  auto _scene = _o->scene.empty() ? 0 : _fbb.CreateString(_o->scene);
  auto _cmd_report_once = _o->cmd_report_once;
  auto _is_signed = _o->is_signed;
  auto _input_breaker = _o->input_breaker;
  auto _player_mode = _o->player_mode;
  auto _set_scene = _o->set_scene.empty() ? 0 : _fbb.CreateString(_o->set_scene);
  auto _set_signiture = _o->set_signiture.empty() ? 0 : _fbb.CreateString(_o->set_signiture);
  auto _set_input_breaker = _o->set_input_breaker;
  auto _set_player_mode = _o->set_player_mode;
  return CreateSrvGlobalParamsMsg(
      _fbb,
      _timestamp,
      _name,
      _sys_id,
      _req_src_id,
      _scene,
      _cmd_report_once,
      _is_signed,
      _input_breaker,
      _player_mode,
      _set_scene,
      _set_signiture,
      _set_input_breaker,
      _set_player_mode);
}

inline const SrvGlobalParamsMsg *GetSrvGlobalParamsMsg(const void *buf) {
  return ::flatbuffers::GetRoot<SrvGlobalParamsMsg>(buf);
}

inline const SrvGlobalParamsMsg *GetSizePrefixedSrvGlobalParamsMsg(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SrvGlobalParamsMsg>(buf);
}

inline const char *SrvGlobalParamsMsgIdentifier() {
  return "S001";
}

inline bool SrvGlobalParamsMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SrvGlobalParamsMsgIdentifier());
}

inline bool SizePrefixedSrvGlobalParamsMsgBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SrvGlobalParamsMsgIdentifier(), true);
}

inline bool VerifySrvGlobalParamsMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SrvGlobalParamsMsg>(SrvGlobalParamsMsgIdentifier());
}

inline bool VerifySizePrefixedSrvGlobalParamsMsgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SrvGlobalParamsMsg>(SrvGlobalParamsMsgIdentifier());
}

inline void FinishSrvGlobalParamsMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SrvGlobalParamsMsg> root) {
  fbb.Finish(root, SrvGlobalParamsMsgIdentifier());
}

inline void FinishSizePrefixedSrvGlobalParamsMsgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SrvGlobalParamsMsg> root) {
  fbb.FinishSizePrefixed(root, SrvGlobalParamsMsgIdentifier());
}

inline std::unique_ptr<SrvGlobalParamsMsgT> UnPackSrvGlobalParamsMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SrvGlobalParamsMsgT>(GetSrvGlobalParamsMsg(buf)->UnPack(res));
}

inline std::unique_ptr<SrvGlobalParamsMsgT> UnPackSizePrefixedSrvGlobalParamsMsg(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SrvGlobalParamsMsgT>(GetSizePrefixedSrvGlobalParamsMsg(buf)->UnPack(res));
}

#endif  // FLATBUFFERS_GENERATED_S001SRVGLOBALPARAMSMSG_H_
